### ISSUE TITLE
Timer in dialogs

### ISSUE THREAD

**Issue by KingTatouille** [SkytAsul/BeautyQuests#101]
**Is your feature request related to a problem?**
Oui, car devoir tout le temps cliquer sur le pnj pour pourvoir lui parler c'est assez embêtant haha ! Mais bon j'aime pas faire le gars exigeant surtout quand le travail est vraiment bien fait et que le plugin est gratuit, je voulais juste savoir si il est possible de faire un dialogue en continue, on clique 1 fois sur le pnj et ensuite le dialogue commence, le pnj parle et ensuite la quête s'active.

**Describe a possible solution**
J'ai tout dis dans le premier paragraphe héhé, voilà c'est une requête basique mais vraiment utile je pense ^^'

Merci en tout cas pour votre super travail !

**Comment by Mortesaison** [comment]
Superbe demande, vu que j'avais également demandé si c'était possible.
Attention tout de même qu'il faudrait prévoir un temps entre les phrases.
En effet, si le joueur ou le PNJ a beaucoup à dire, il faut laisser le temps de le lire.
Pareil dans l'autre sens, si le texte est court, ça ne sert à rien d'attendre 10 sec la phrase suivante.
Ce serait donc bien d'avoir un choix de temps d'attente à chaque phrase.
Ex: 
`startDialog:
  npc: 116
  msgs:
  - id: 0
    message:
      sender: NPC
      text: Hello, est-ce que tu peux trouver une fleur spéciale? C'est vraiment important pour moi et pour une autre personne.
      wait: 5 #attente de 5 sec
  - id: 1
    message:
      sender: PLAYER
      text: &2bien, il faut être plus convaincant
      wait: 2 #attente de 2 sec
  - id: 2
    message:
      sender: NPC
      text: J'en ai besoin pour une expérience
      wait: 2 #attente de 2 sec
  - id: 3
    message:
      sender: PLAYER
      text: &2OK
      wait: 1 #attente de 1 sec
...

**Comment by KingTatouille** [comment]
Yes ! 💃

**Comment by SkytAsul** [comment]
Tout est bon pour moi ! Ce sera fait pour la 0.17.

**Comment by KingTatouille** [comment]
Merci ! ❤️

**Comment by SkytAsul** [comment]
Tututut, on ne close pas l'issue tant que la feature n'est pas mise !

**Comment by SkytAsul** [comment]
Terminé dans le commit https://github.com/SkytAsul/BeautyQuests/commit/57783f5b1ec594f9dae3ec5023b1eb820e73ea1f
Inclus dans la [build 43](https://ci.codemc.io/job/SkytAsul/job/BeautyQuests/43/).
