### ISSUE TITLE
boss

### ISSUE THREAD

**Issue by CotedeBoeuff** [SkytAsul/BeautyQuests#103]
Bonjour,

Comment puis-je faire pour donner un mob à tuer à une quête quand ces un boss qui vien du plugin Boss et non de votre plugin EpicBosse ?

Cordialement

**Comment by SkytAsul** [comment]
[Ce plugin-là](https://www.spigotmc.org/resources/%E2%98%9B-boss%E2%84%A2-custom-monsters-and-animals-on-your-server-1-8-9-1-14-4.46497/) ? Je vais l'ajouter à ma liste de choses à faire !

**Comment by CotedeBoeuff** [comment]
Bonjour,

Parfait ces celui-ci, merci

**Comment by SkytAsul** [comment]
Fini avec https://github.com/SkytAsul/BeautyQuests/commit/b1be80ca8d698e6bdf33576164cd56d334f93f38, présent dans la dev build [#49](https://ci.codemc.io/job/SkytAsul/job/BeautyQuests/49/).
