### ISSUE TITLE
Bug reset

### ISSUE THREAD

**Issue by CotedeBoeuff** [SkytAsul/BeautyQuests#107]
Bonjour,

Les quêtes de mes joueurs se reset très souvent je ne trouve pas d’où vien ce problème... 
Mon serveur est en version 1.14 et la version du plugin est en 1.14 aussi.

Merci 
Cordialement

**Comment by SkytAsul** [comment]
Il n'y a pas de version 1.14 pour le plugin :/ fais `/quests version` et envoie le résultat ici pour voir un peu.

**Comment by CotedeBoeuff** [comment]
Voici ma version ci dessous.

**Comment by SkytAsul** [comment]
Euh je crois que ton message s'est mal envoyé...

**Comment by CotedeBoeuff** [comment]
Vous n'aurez pas un discord cela serait plus simple ?

**Comment by CotedeBoeuff** [comment]
Le jeu. 19 déc. 2019 à 18:35, Clément ONFROY <clement91.onfroy@gmail.com> a
écrit :

**Comment by SkytAsul** [comment]
Si bien sûr : https://discord.gg/H8fXrkD

**Comment by SkytAsul** [comment]
Le bug a sûrement été résolu avec le nouveau système de données.
