### ISSUE TITLE
MythicMobs Vanilla Mobs with levels

### ISSUE THREAD

**Issue by SrJuggernaut** [SkytAsul/BeautyQuests#109]
**Is your feature request related to a problem?**
I use MythicMobs to make the default Vanilla Mobs level, when i tried to make a quest where the player kill 10 - Zombies lvl 10 the plugin dont recognize them

**Describe a possible solution**
Add Support for Vanilla Overrides on BeatyQuest

(FR: Si vous êtes plus facilement compréhensible en français, écrivez dans cette langue car il s'agit de ma langue natale)

**Comment by SkytAsul** [comment]
Present in BeautyQuestsAddon.
