### ISSUE TITLE
Scoreboard gets stuck on "loading"

### ISSUE THREAD

**Issue by imparium-de** [SkytAsul/BeautyQuests#111]
**Describe the bug**	
When having an active quest, the scoreboard sometimes gets stuck on "loading". It seems to be related with leaving the server / switching the server in a bungeecord network, but we're not 100% sure.

**Reproduction**
Steps to reproduce the behavior. (If not already explained above.)

**Screenshots, error messages**
![image](https://user-images.githubusercontent.com/63745647/79394788-96bd1a80-7f78-11ea-8b18-72ba231f93fb.png)

**Software**
BeautyQuests version: 0.17_BUILD70
Game version: 1.15.2
Server version: 1.15.2
Server type (e.i. PaperSpigot): git-Paper-161 (MC: 1.15.2)
Are you using a protocol hack (like ViaVersion)?: No

**Additional context (optional)**
It doesn't affect the actual quest or the boss bar. Everything is working as expected.
EDIT: It fixes itself when progressing in the quest. For example: In a fishing quest after getting a fish.

(FR: Si vous êtes plus facilement compréhensible en français, écrivez dans cette langue car il s'agit de ma langue natale)

**Comment by SkytAsul** [comment]
This bug has been fixed in dev build #73. You should consider updating to the [latest one (#79)](https://ci.codemc.io/job/SkytAsul/job/BeautyQuests/79/artifact/target/beautyquests-0.17.0-SNAPSHOT.jar).
