### ISSUE TITLE
more quests required

### ISSUE THREAD

**Issue by BlakHord** [SkytAsul/BeautyQuests#112]
Si ça serait possible d’ajouter plus de quêtes requise dans le requirment car avec une seul on ne peut pas faire tout ce que l'on veux. C'est juste une idée

**Comment by Azuu22** [comment]
Je suis d'accord, je lui ai déjà proposé sur Discord, et sur GitHub ça ne fait pas de mal ^^. Après il y a pour le moment l'alternative du "permission(s) requise(s) mais bon, ce serait quand même plus simple ça :D !

**Comment by SkytAsul** [comment]
Fini avec https://github.com/SkytAsul/BeautyQuests/commit/822f3f8c2934c669943b9af1694d9b95b9cc1ef2

**Comment by SkytAsul** [comment]
My bad, c'est pas encore fini 😅

**Comment by Azuuno** [comment]
Bouuuuh

**Comment by SkytAsul** [comment]
Fini avec https://github.com/SkytAsul/BeautyQuests/commit/e3fcdd8059fb86e658bd7c2ae9122884ef455b9f
