### ISSUE TITLE
changer l'item représentant une quete dans le menu du pnj 

### ISSUE THREAD

**Issue by hacecah** [SkytAsul/BeautyQuests#113]
_**Is your feature request related to a problem?**_
The item that represents a quest in the menu (when a NPC have many quests to give) is a book, we cant change it.
**L'objet représentant la quête dans le menu (le menu quand un pnj a plusiseurs quetes à proposer) est un livre et on ne peut pas changer cela (choisir un item reflètant ler type de quete genre pioche pour le minage, arc pour la chasse et tout....)**

_**Describe a possible solution**_
It will be interresting to add a config to choose the quest's item in the menu
**ça serait cool d'ajouter un epossibilité de choisir l'objet représentant une quete dans le menu du pnj**

**Comment by SkytAsul** [comment]
Ajouté à la 0.17.
