### ISSUE TITLE
[FR] Impossible de fermer l'éditeur chat

### ISSUE THREAD

**Issue by AvnyrTokirawa** [SkytAsul/BeautyQuests#114]
**Impossible de fermer l'éditeur chat avec "close", "cancel" et /quests editor (non reconnu)**

S'applique lors de l'édition d'une ou plusieurs variable dans le menu chat,
Par exemple **donner l'ID d'un objet**

J'ai l'impression qu'il ne reconnait pas l'entrée  "close" ou "cancel"

**Screenshots**
http://proxy.avnyr.org/src/bq_bug_cancelclose.png

**Software**
BeautyQuests version: **0.16.1 < 0.17_Build79**
Game version: **1.15.2**
Server version: **1.15.2**
Server type : **git-Spigot-800b93f-8160e29**
Proxy : **Bungeecord**

**Autre**
J'ai des membres de mon staff qui me rapporte des erreurs similaires toujours dans l'édition chat mais pour d'autre tache.
Si vous souhaitez vous rendre sur le serveur mc pour jeter un coup d'œil vous même n'hésitez pas à me le dire.

Cordialement, Avnyr Tokirawa
Fondateur du Secteur 42
contact@secteur42.org
(secteur42.avnyr.org)

**Comment by SkytAsul** [comment]
Fixé !
