### ISSUE TITLE
NPC qui change d'emplacement

### ISSUE THREAD

**Issue by AvnyrTokirawa** [SkytAsul/BeautyQuests#115]
Possibilité que le NPC sois déplacé ou suive le joueur (follow/guard) 
exemple:
Enfant perdu dans les montagnes, il faut le ramener au village sain et sauf (peux se faire focus par les mobs et mourir temporairement)

**Comment by SkytAsul** [comment]
L'idée est intéressante et sera sûrement implémentée dans le futur, pourquoi fermer l'issue?
