### ISSUE TITLE
Honey Bottle can't be set as reward (edit: anything related to bees is the same)

### ISSUE THREAD

**Issue by Kyraito2** [SkytAsul/BeautyQuests#116]
**Describe the bug**	
Lors d'une quête où il faut rammener un objet, mettre une bouteille de miel comme objet à rammener et valider la quête cause une erreur et retire l'étape. 

During a fetch quest creation, setting honey bottles as the required item and validating the quest causes an error and deletes the fetch stage.
**Reproduction**
Explained above
**Screenshots, error messages**
![image](https://user-images.githubusercontent.com/64565007/80659598-45b02a80-8a3e-11ea-88bd-7708dd9499a7.png)

`[02:17:37] [Server thread/WARN]: java.lang.IllegalArgumentException: No enum constant fr.skytasul.quests.utils.XMaterial.HONEY_BOTTLE[02:17:37] [Server thread/WARN]: at java.lang.Enum.valueOf(Enum.java:238)[02:17:37] [Server thread/WARN]: at fr.skytasul.quests.utils.XMaterial.valueOf(XMaterial.java:15)[02:17:37] [Server thread/WARN]: at fr.skytasul.quests.utils.XMaterial.fromItemStack(XMaterial.java:1162)[02:17:37] [Server thread/WARN]: at fr.skytasul.quests.gui.ItemUtils.getName(ItemUtils.java:167)[02:17:37] [Server thread/WARN]: at fr.skytasul.quests.utils.Utils.getStringFromItemStack(Utils.java:98)[02:17:37] [Server thread/WARN]: at fr.skytasul.quests.stages.StageBringBack.(StageBringBack.java:41)[02:17:37] [Server thread/WARN]: at fr.skytasul.quests.gui.creation.stages.CreateBringBack.finish(StagesGUI.java:479)[02:17:37] [Server thread/WARN]: at fr.skytasul.quests.gui.creation.FinishGUI.loadBranch(FinishGUI.java:419)[02:17:37] [Server thread/WARN]: at fr.skytasul.quests.gui.creation.FinishGUI.finish(FinishGUI.java:387)[02:17:37] [Server thread/WARN]: at fr.skytasul.quests.gui.creation.FinishGUI.onClick(FinishGUI.java:321)[02:17:37] [Server thread/WARN]: at fr.skytasul.quests.gui.Inventories.onClick(Inventories.java:66)[02:17:37] [Server thread/WARN]: at fr.skytasul.quests.QuestsListener.onClick(QuestsListener.java:101)[02:17:37] [Server thread/WARN]: at sun.reflect.GeneratedMethodAccessor90.invoke(Unknown Source)[02:17:37] [Server thread/WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[02:17:37] [Server thread/WARN]: at java.lang.reflect.Method.invoke(Method.java:498)[02:17:37] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316)[02:17:37] [Server thread/WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)[02:17:37] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529)[02:17:37] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514)[02:17:37] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2147)[02:17:37] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:32)[02:17:37] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:10)[02:17:37] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19)[02:17:37] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18)[02:17:37] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144)[02:17:37] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)[02:17:37] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118)[02:17:37] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918)[02:17:37] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911)[02:17:37] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127)[02:17:37] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:895)[02:17:37] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828)[02:17:37] [Server thread/WARN]: at java.lang.Thread.run(Thread.java:748)`

**Software**
BeautyQuests version: 0.16.1 (updated to 0.16.2 but still displays 0.16.1 when executing /bq version)
Game version: 1.15.2
Server version: 1.52.2
Server type (e.i. PaperSpigot): Spigot
Are you using a protocol hack (like ViaVersion)? No

**Additional context (optional)**
N/A

(FR: Si vous êtes plus facilement compréhensible en français, écrivez dans cette langue car il s'agit de ma langue natale)

**Comment by SkytAsul** [comment]
C'est un soucis qui a été corrigé dans les dev build !

**Comment by Kyraito2** [comment]
:)
