### ISSUE TITLE
Sub Categories and bypass npc needed to create Quest

### ISSUE THREAD

**Issue by yippy9** [SkytAsul/BeautyQuests#117]
**Is your feature request related to a problem?**
Frustrated that i cant create a quest without needing an npc and would love a sub category system 
**Describe a possible solution**
implement them if possible
**Describe alternatives you've considered (optional)**

**Additional context (optional)**

(FR: Si vous êtes plus facilement compréhensible en français, écrivez dans cette langue car il s'agit de ma langue natale)

**Comment by SkytAsul** [comment]
NPC are no longer needed since 0.18 and 0.19 introduced quest pools!
