### ISSUE TITLE
Few more quest features?

### ISSUE THREAD

**Issue by yippy9** [SkytAsul/BeautyQuests#119]
**Is your feature request related to a problem?**
A clear and concise description of what the problem is. E.g. "I'm always frustrated when [...]"
Would it be possible so that if specific item was in your inventory you would complete a quest so if you got 2 stacks of diamonds in the inventory you would complete it? and possibly a distanced travelled if you where asked to run 1k blocks?

**Comment by SkytAsul** [comment]
Distance travelled is possible with the expansion, items in your inventory is achievable with "bring items to npc".
