### ISSUE TITLE
AbstractRequirement API making many calls every second

### ISSUE THREAD

**Issue by sebastiendeu** [SkytAsul/BeautyQuests#122]
**Describe the bug**	
I have a custom requirement for my RP server. When I have implemented the AbstractRequirement class, I have overridden test function with database call. But actually my database is solicited every second when player(s) is/are in the same chunk of NPC with this requirement. 

If on the same chunk I have multiple NPC with this requirement the every second call is multiplied by the number of NPC in the chunk. Moreover player(s) in this chunk don't have any quest started when these calls are made.

My database is too solicited do you have a solution ? I have already implemented a cache solution.

**Screenshots, error messages**
https://cdn.discordapp.com/attachments/400772010361356289/711991982834057256/2020-05-18-192122_491x491_scrot.png

**Software**
BeautyQuests version: 0.17.0-SNAPSHOT
Game version: 1.15.2
Server version: 1.15.2
Server type (e.i. PaperSpigot): Paper
Are you using a protocol hack (like ViaVersion)? NO

**Comment by SkytAsul** [comment]
Requirements are tested every second to check if the player can start the quest and to display particles over NPC's head.
You can cache your database data and refresh it like every minute for instance. If it's a player data stored in the db then it would be more complicated. Could you describe a little more what you're trying to do?

**Comment by sebastiendeu** [comment]
This check is very aggressive. I have 10-13 NPC with 5 players around them. 

My database contains players data with a website in front. I can't permit one plugin to overflow its connection pool. I have another plugin on this database for access management, whitelist, ...

Can I reduce this check interval ? Or is it possible to launch this check only when a player click to start a quest ?

**Comment by SkytAsul** [comment]
Well, you could run a bukkit task which updates a cache for this DB data every minute and it will work... but from a programming aspect, it is not really good.
The best way would be that, when the data is updated from the website or whatever, you send the update to the server with the protocol you want (Redis, Bungeecord if it's updated via the proxy, JsonAPI...).
