### ISSUE TITLE
Bug in the mission to kill mobs

### ISSUE THREAD

**Issue by RafaPS98** [SkytAsul/BeautyQuests#124]
I create a mission to kill mobs, but when I kill, the mission doesn't work. tried everything and nothing works.

EX: npc 1 talks to npc 2 and npc 2 gives me mission to kill mobs, even killing, the mission does not end

**Comment by SkytAsul** [comment]
Which version of BeautyQuests are you using?
Also, could you send me the quest file and a list of which plugins installed on your server?

**Comment by RafaPS98** [comment]
I'm using the latest version (0.17 build 92) I'll send the attachment with the server plugins. are more than 120 active plugins at the moment because it is a server rpg
![Screenshot_1](https://user-images.githubusercontent.com/66890215/84595660-7fdb5d00-ae2f-11ea-9753-c6888301a7b0.png)
![Screenshot_2](https://user-images.githubusercontent.com/66890215/84595662-82d64d80-ae2f-11ea-87ea-48b11fda72d8.png)

**Comment by RafaPS98** [comment]
The mission is to kill 5 cows, when I kill the mission not complete. the scoreboard is locked at 5x
![Screenshot_3](https://user-images.githubusercontent.com/66890215/84596065-d9448b80-ae31-11ea-8005-18c7beda99a5.png)

**Comment by SkytAsul** [comment]
Another plugin is interfering, I can't see other reasons. There is no errors in console at the server starting or when you kill the cows?

**Comment by RafaPS98** [comment]
There are several bugs in the console, anyway, thanks for the attention and help. Unfortunately, I will change the plugin.
but anyway thank you

**Comment by SkytAsul** [comment]
I accept that, thus I recommend you to check the console first before reporting a bug, it will save you time and developers will be able to help you more easily. "it doesn't work" is not enough for us.
