### ISSUE TITLE
Could not pass event InventoryClickEvent to BeautyQuests v0.17

### ISSUE THREAD

**Issue by scorninpc** [SkytAsul/BeautyQuests#125]
**Describe the bug**	
Some index error are possibiliting remove books from GUI Inventory on /quests

**Reproduction**
Just open /quests GUI, and click on books. Each click remove one letter from title. When title finish, the book can be removed from GUI

**Screenshots, error messages**
Video: https://youtu.be/C9hJIgQ5BTg
Log: https://pastebin.com/e6XZEyW4

**Software**
BeautyQuests version: 0.17
Game version: 1.16.1
Server version: paper 1.16.1
Server type (e.i. PaperSpigot): Paper
Are you using a protocol hack (like ViaVersion)? no

**Comment by SkytAsul** [comment]
Fixed with https://github.com/SkytAsul/BeautyQuests/commit/c397e5c58e7c1b23e7636d24877eef260a8ee8ca

**Comment by scorninpc** [comment]
Man, this plugin are awesome, and your work is great. Thank you
