### ISSUE TITLE
Make empty quest scoreboard placeholder editable

### ISSUE THREAD

**Issue by tedders5** [SkytAsul/BeautyQuests#126]
Add the option in the scoreboard config to edit this: http://puu.sh/G4soY/b9da475c19.png

and make the "loading" placeholders custom text.

**Comment by SkytAsul** [comment]
Sorry, I haven't got notification for this issue. Those placeholders are editable in the lang file, lines `scoreboard.noLaunchedName` and `scoreboard.noLaunchedDescription`.
