### ISSUE TITLE
NPCs with multiple quests do not display the "you must have finished the quest" message

### ISSUE THREAD

**Issue by tedders5** [SkytAsul/BeautyQuests#127]
**Describe the bug**	
Clicking a NPC without doing its quest requirements first usually shows the error message: "you must have finished the quest [quest]". This is working fine when the NPC only has one quest. However when a NPC has multiple quests, there is no error message shown.

**Reproduction**
Click on a NPC with multiple quests and quest requirements.

**Screenshots, error messages**
http://puu.sh/G4vHH/40ec733688.png

**Software**
BeautyQuests version: 0.17.1_BUILD100
Game version: 1.15.2
Server version: 1.15.2
Server type (e.i. PaperSpigot): PaperSpigot
Are you using a protocol hack (like ViaVersion)? no

(FR: Si vous êtes plus facilement compréhensible en français, écrivez dans cette langue car il s'agit de ma langue natale)

**Comment by SkytAsul** [comment]
Fixed in https://github.com/SkytAsul/BeautyQuests/commit/c07cef262d5ab5ff845e4532c9e6fa8cf944db5e by adding the config option `requirementReasonOnMultipleQuests`.
