### ISSUE TITLE
MMOCore and MMOItems support

### ISSUE THREAD

**Issue by kiloRs** [SkytAsul/BeautyQuests#129]
Requesting support for MMOCore RPG plugin, and MMOItems item creation plugin.

**Comment by EnderGriefeur99** [comment]
you can drag and drop the items from mmoitems and pm me on discord for the mmocore support i coded an extension for that Ender_Griefeur99#4856

**Comment by kiloRs** [comment]
Oh did u really? Uh ok sorry i didnt know u could drag and drop. Do u take
suggestions for other aspects

**Comment by EnderGriefeur99** [comment]
yes

**Comment by EnderGriefeur99** [comment]
yes and yes ^^

**Comment by Hypocisy** [comment]
I hope this will be updated soon!!

**Comment by EnderGriefeur99** [comment]
--> link for my addon i release the update today https://www.spigotmc.org/resources/beautyquestsaddon.79132/
