### ISSUE TITLE
Quête ayant pour objectif d'écrire une commande

### ISSUE THREAD

**Issue by kahiii** [SkytAsul/BeautyQuests#13]
Salut sky,

Pourrais-tu rajouter comme objectif l'écriture d'une commande par exemple un pnj te demande de taper la commande /reglement afin de passer à l'étape supérieur :)

merci ;)

**Comment by SkytAsul** [comment]
Ce genre d'étapes ne rentre pas trop dans un esprit RP, qui est quand même la base de BeautyQuests... C'est pour faire un genre de quêtes tutoriel ?

**Comment by SkytAsul** [comment]
Added in 0.12
