### ISSUE TITLE
Citizens Text interactions take priority over starting the quest.

### ISSUE THREAD

**Issue by barosielle** [SkytAsul/BeautyQuests#132]
I'm not really sure if this is a bug or if I'm just being stupid, but I can't seem to start a quest. The NPC quest starter also has random text dialogue, and when you interact with him he just talks to you. I should be able to right-click on the NPC to start the quest, but it doesn't work.

![2020-07-18_15 09 05](https://user-images.githubusercontent.com/68481310/87861160-2d4b0000-c909-11ea-8988-e59b7294d896.png)

BeautyQuests version: 0.17
Game version: 1.16.1
Server version: Paper version git-Paper-86 (it didnt really give me a version)
Server type (e.i. PaperSpigot):

**Comment by EnderGriefeur99** [comment]
use my config file 
``# Citizens Configuration

general:
  authlib:
    profile-url: https://sessionserver.mojang.com/session/minecraft/profile/
  debug-file: ''
  debug-mode: false
  debug-pathfinding: false
  color-scheme:
    message-highlight: <e>
    message: <a>
    message-error: <c>
  translation:
    locale: ''
npc:
  chat:
    options:
      bystanders-hear-targeted-chat: true
      max-number-of-targets-to-show: 2
      multiple-targets-format: <target>|, <target>| & <target>| & others
      range: 5
      max-text-range: 500
    format:
      no-targets: '[<npc>]: <text>'
      with-target-to-bystanders: '[<npc>] -> [<target>]: <text>'
      to-target: '[<npc>] -> You: <text>'
      with-targets-to-bystanders: '[<npc>] -> [<targets>]: <text>'
  pathfinding:
    default-distance-margin: 2
    update-path-rate: 20
    maximum-new-pathfinder-iterations: 50000
    new-finder-open-doors: false
    attack-range: 3.0625
    use-new-finder: false
    new-finder:
      iterations-per-tick: 25000
      check-bounding-boxes: false
      open-doors: false
    default-path-distance-margin: 1
    disable-mc-fallback-navigation: true
  default:
    look-close:
      enabled: false
      range: 5
      random-look-enabled: false
      random-look-delay: 60
      disable-while-navigating: true
    pathfinding:
      range: 25.0
    random-talker: true
    realistic-looking: false
    stationary-ticks: -1
    talk-close:
      enabled: false
      range: 5
    text:
      '0': Hi, I'm <npc>!
    waypoints:
      cache-paths: false
  limits:
    default-limit: 10
    max-permission-checks: 100
    max-packet-entries: 15
    max-speed: 100
  tablist:
    disable: true
  chunks:
    always-keep-loaded: false
  skins:
    max-retries: -1
    retry-delay: 120
    rotation-update-degrees: 90.0
    use-latest-by-default: false
    view-distance: 100.0
  packets:
    update-delay: 30
  selection:
    quick-select: false
    item: '280'
    message: <b>You selected <a><npc><b>!
  player:
    remove-from-list: true
  server-ownership: false
  text:
    max-talk-cooldown: 5
    min-talk-cooldown: 10
    talk-item: '340'
  teleport-delay: -1
  controllable:
    use-boat-controls: true
    ground-direction-modifier: 1.0
    max-ground-speed: 0.5
  player-scoreboard-teams:
    enable: true
  hologram:
    default-line-height: 0.4
advanced:
  check-minecraft-version: true
economy:
  npc:
    cost: 100.0
storage:
  save-task:
    delay: 72000
  file: saves.yml
  type: yaml
subplugins:
  folder: plugins
``

**Comment by barosielle** [comment]
Do I paste the raw text or the first text?

**Comment by EnderGriefeur99** [comment]
take all
