### ISSUE TITLE
Kill quest tracker

### ISSUE THREAD

**Issue by karuney** [SkytAsul/BeautyQuests#133]
I have noticed and I cannot tell if it that I am blind as heck but with kill quests there is no way to track your progress in it. 

For example I have a quest that is kill 100 zombies and my players have no way to tell how many they have killed. So if I am just being dumb and not seeing cool, if not this feature would be super amazing.

**Comment by SkytAsul** [comment]
There are several ways to track the amount of mobs killed:
> Set `mobsProgressBar: true` in _config.yml_.
> When the player open their quest menu they can see on the quest item.
> If you have enabled the scoreboard, they can see on it.

**Comment by karuney** [comment]
I have scoreboard enabled and they claim they can't see it. Is there a permission attached to it that isn't listed?

**Comment by SkytAsul** [comment]
No... you're using the BeautyQuests' scoreboard or one from another plugin?

**Comment by karuney** [comment]
beautyquest scoreboard

**Comment by karuney** [comment]
A bossbar will show up now with the overall progress of the mob kills but they don't see a scoreboard. Also the boss bar shows overall progress and not the individual progress (example: zombie 1/50 spider 3/45 skeleton 1/10 )

**Comment by SkytAsul** [comment]
Could you check if the line `scoreboards` is set to `true` in _config.yml_ and also send me the content of _scoreboard.yml_?

**Comment by karuney** [comment]
`# Configuration relative to quests
quests:
  # Time in seconds before the quest tracker switch
  changeTime: 10
  # If enabled and the player has no quest launched, the scoreboard will disappear until the player starts a new quest
  hideIfEmpty: true
  # If enabled, scoreboard lines containing {questName} or {questDescription} will be automatically refreshed whenever the quest tracker is refreshed
  refreshLines: true

# Lines contained in the scoreboard
#  Available parameters:
#  * value: the value of line, surrounded by '
#   -> special placehlolders: {questName} and {questDescription}
#  * refresh: time in seconds before the line is refreshed (useful with dynamic placeholders)
#  * length: max length of the line, if the number of characters exceed this limit the line will be split
lines:
- value: ''
- value: '&6{questName}'
- value: ''
- value: '{questDescription}'
  length: 30
  `

**Comment by karuney** [comment]
> # Configuration relative to quests
quests:
  # Time in seconds before the quest tracker switch
  changeTime: 10
  # If enabled and the player has no quest launched, the scoreboard will disappear until the player starts a new quest
  hideIfEmpty: true
  # If enabled, scoreboard lines containing {questName} or {questDescription} will be automatically refreshed whenever the quest tracker is refreshed
  refreshLines: true

# Lines contained in the scoreboard
#  Available parameters:
#  * value: the value of line, surrounded by '
#   -> special placehlolders: {questName} and {questDescription}
#  * refresh: time in seconds before the line is refreshed (useful with dynamic placeholders)
#  * length: max length of the line, if the number of characters exceed this limit the line will be split
lines:
- value: ''
- value: '&6{questName}'
- value: ''
- value: '{questDescription}'
  length: 30

**Comment by karuney** [comment]
https://pastebin.com/BkquR1iP

**Comment by SkytAsul** [comment]
Dormant issue. Please reopen if this is still an issue, even with latest dev build.
