### ISSUE TITLE
When editing tasks with GUI, clicking OK has no effect!

### ISSUE THREAD

**Issue by JiuTianlang** [SkytAsul/BeautyQuests#135]

**Comment by EnderGriefeur99** [comment]
Any msg of error ?

**Comment by JiuTianlang** [comment]
> Any msg of error ?

No,there is nothing

**Comment by JiuTianlang** [comment]
> Any msg of error ?

I click it ,and nothing has happened

**Comment by SkytAsul** [comment]
Any news regarding this issue with latest 0.18 version?

**Comment by Zopiote** [comment]
hello i've same problem in 0.18 version :/

**Comment by SkytAsul** [comment]
Any news regarding this issue with latest 0.19 dev builds?

**Comment by SkytAsul** [comment]
I assume this has been fixed.
