### ISSUE TITLE
No response when type in commands

### ISSUE THREAD

**Issue by BrownXu321123456** [SkytAsul/BeautyQuests#136]
First of all I want to thank for your work on this outstanding plugin, I used it before it is really good. But there is a problem. recently I update my server into 1.16.2 and installed the latest citizen and beauty quest. The install seems to be success, when starting the server there are no error reports, but after I get into the server, every command I type there are no responses, its just nothing happened, no error messages or feedback.
I'm not a professional programmer and I can not find what's wrong , please help.

Both 0.17.3 and 0.17.4 versions of the plug have the same issue for me.

thanks.

**Comment by EnderGriefeur99** [comment]
you can find the dev builds on the [discord](https://discord.gg/H8fXrkD), the last dev builds support the 1.16.2

**Comment by BrownXu321123456** [comment]
Ohhh, I got it. Thanks so much!
