### ISSUE TITLE
Mine/place glitch on 1.12.2

### ISSUE THREAD

**Issue by ToaztyXD** [SkytAsul/BeautyQuests#138]
I am trying to make a quest where they have to mine 50 cobblestone but even when i mine 50 cobblestone it still doesn't count it. All the other quests work execpt mining and placing. Is it because my server is on 1.12.2? please get back to me soon.

**Comment by SkytAsul** [comment]
Do you have a custom mining plugin like an ore replacer or smthg like that?

**Comment by ToaztyXD** [comment]
I deleted that plugin and it still doesn't seem to work. It also doesn't work with placing blocks but everything else works great. 
For placing blocks it says unknown string below the quest name which is really weird. But I did find an error message in my console: ERROR Could not pass event BlockBreakEvent to BeautyQuests v0.18_PRE
I don't know what this means so if you could help me figure it out that would be great! :)

**Comment by SkytAsul** [comment]
Could you upgrade to the latest dev build (available [here](https://ci.codemc.io/job/SkytAsul/job/BeautyQuests/152/artifact/target/beautyquests-0.18.0-SNAPSHOT.jar)) and send me the complete error if this still happens?

**Comment by ToaztyXD** [comment]
it still doesn't work and this is the entire error: https://pastebin.com/xt61rKCx

**Comment by SkytAsul** [comment]
Hmm this seems like an unrelated error... I just fixed it, try with the dev build 154 and check if the "mine blocks" thing is still failing.

**Comment by ToaztyXD** [comment]
it is still failing with the same error message even when i used your new link. It might be a plugin I have that is stopping it but does it work for other people?

**Comment by SkytAsul** [comment]
The previous error is now impossible so I think you're not using build 154. Just download the latest one here https://ci.codemc.io/job/SkytAsul/job/BeautyQuests/
With this one, you will be able to start the quest and when mining a block, either it just work with a fix I previously added, either it will fail with *another* error that I will need.

**Comment by ToaztyXD** [comment]
I restarted the website but the build 154 is not there for me. I went to the link you gave me and downloaded the latest version but it still gave me the 153 error which means either I'm really stupid or the link for the 154 build isn't there because even when i search for the number 154 nothing comes up.

**Comment by SkytAsul** [comment]
Yes the build 154 had an error on build so the latest one is 156. I don't think you're having the exact same error than with the previous build so please send me the new one, there must be some differences.

**Comment by ToaztyXD** [comment]
I cleared my console log and this is what happend after I mined a block well the mining quest was active: https://pastebin.com/5dTZXekz

**Comment by SkytAsul** [comment]
OK this is definitely the error I was looking for ^^
Your server is on a previous-1.13 version right? I'll try to see how to fix this.

**Comment by ToaztyXD** [comment]
Sorry for the late response and I really appreciate you helping but it still gave me an error and I never had my server on 1.13 but I have used some other versions like 1.8. The error that it said was: https://pastebin.com/si5XRd6A (for the #157 build) and this is what the error is for the latest build (#161) https://pastebin.com/D37ztkTU

**Comment by SkytAsul** [comment]
Fixed in the Pre-release 2! https://www.spigotmc.org/resources/beautyquests.39255/update?update=366752
(dev build #162)
