### ISSUE TITLE
Option "Region required" doesn't wait for Value Input

### ISSUE THREAD

**Issue by Crousus** [SkytAsul/BeautyQuests#139]
**Describe the bug**	
When creating a Quest step that requires a certain region, it doesnt let you enter the name in the Chat. It skips that step and uses "null" as Region Name.

**Screenshots, error messages**
![Unbenannt](https://user-images.githubusercontent.com/19433560/96578978-6020dd80-12d6-11eb-8665-029959658ecb.PNG)

**Software**
BeautyQuests version: 0.18_BUILD161
Game version: 1.16.3
Server version: 1.16.3
Server type (e.i. PaperSpigot): Paper
Are you using a protocol hack (like ViaVersion)? No

**Comment by SkytAsul** [comment]
Fixed in the Pre-release 2! https://www.spigotmc.org/resources/beautyquests.39255/update?update=366752
(dev build #162)
