### ISSUE TITLE
NullPointerException (PlayerInteractEvent)

### ISSUE THREAD

**Issue by derMiepz** [SkytAsul/BeautyQuests#143]
**Describe the bug**	
Can't really explain how it happened, and I also don't have reproduction steps since I noticed the message in the console pretty late. The plugin seems to work like expected, even after the error.

**Screenshots, error messages**
Error message: https://pastebin.com/AZvdje38

**Software**
BeautyQuests version: 0.19.0_BUILD174
Game version: 1.16.4
Server version: 1.16.4
Server type (e.i. PaperSpigot): Paper
Are you using a protocol hack (like ViaVersion)? Yes

**Additional context (optional)**
Plugin continues to work as expected

**Comment by SkytAsul** [comment]
Fine! I'm fixing this ^^

**Comment by derMiepz** [comment]
Thanks! ❤️
