### ISSUE TITLE
Quest Requirement not working

### ISSUE THREAD

**Issue by Xuan1418** [SkytAsul/BeautyQuests#145]
**Describe the bug**	
I had set the placeholder requirement to start as follow
![2020-12-12_16 15 51](https://user-images.githubusercontent.com/69707719/101979199-f3064480-3c95-11eb-9840-5182bfe9b84c.png)
But since like this requirement not working as I cant take quest after I reach the requirement
![2020-12-12_16 24 12](https://user-images.githubusercontent.com/69707719/101979265-a4a57580-3c96-11eb-9a31-57aafa64aa27.png)

**Software**
BeautyQuests version: 0.19.0_BUILD174
Game version: Minecraft 1.16.3
Server version: Paperspigot 1.16.3 - R0.1-Snapshot
Server type (e.i. PaperSpigot): PaperSpigot
Are you using a protocol hack (like ViaVersion)? Yes

(FR: Si vous êtes plus facilement compréhensible en français, écrivez dans cette langue car il s'agit de ma langue natale)

**Comment by SkytAsul** [comment]
Numeric values in placeholders are still experimental - you can edit the quest file and put `GREATER_OR_EQUAL` instead of `EQUALS` under the "comparison" line of your Placeholder Requirement.

**Comment by Xuan1418** [comment]
mean that I need to edit `GREATER` in the quest file?

**Comment by SkytAsul** [comment]
You need to change `comparison: EQUALS` to `comparison: GREATER_OR_EQUAL`

**Comment by SkytAsul** [comment]
Must be fixed.
