### ISSUE TITLE
Enter a password

### ISSUE THREAD

**Issue by marvinej** [SkytAsul/BeautyQuests#15]
**Describe the solution you'd like**
I would like the ability to make a player have to reply back with a password text as a step in a quest, for example they have to examine a room and find the password to continue.

**Describe alternatives you've considered**
I looked at the enter text option but thats not what im looking for. I need to be able to prompt them "whats the password" or "whats the pin" and not tell them what it is.

**Comment by SkytAsul** [comment]
The problem with the Chat Stage Type is that it tells you what to write, am I right ? Because you can edit the description message when creating the quest (the sign item at the right of the line).
