### ISSUE TITLE
[HELP] NPC Quest not working

### ISSUE THREAD

**Issue by Ov3rPowerD** [SkytAsul/BeautyQuests#158]
I set it to start when you click on an npc, but when you click on it, it doesn't work. Is this a bug or am i stupid.

**Comment by Ov3rPowerD** [comment]
Apparently I went back and saw an issue about having Citizens text overriding a quest dialouge. So I removed it and now it just says "Hi im NPC!"

**Comment by EnderGriefeur99** [comment]
use my config file this issue is due to a bad configuration of the citizens config.yml file
https://pastebin.com/3hbCRyhx

**Comment by SkytAsul** [comment]
Issue due to a bad Citizens configuration
