### ISSUE TITLE
Cant Add NPC's to kill

### ISSUE THREAD

**Issue by MrKippo** [SkytAsul/BeautyQuests#159]
**Describe the bug**	
When I try to make one of my objectives to kill an NPC (Sentry), it has me go through the stages to set it up where I select the npc and choose how mant to kill, but then after I press enter, it just opens up the GUI and doesnt actually add the NPC to the list.

**Software**
BeautyQuests version: 0.18.5
Game version: 1.12.2
Server version: 1.12.2
Server type: Spigot
Are you using a protocol hack (like ViaVersion): No, Only on the hub server, not on the server that beautyquests is installed on.

**Comment by SkytAsul** [comment]
Can you try with the latest 0.19 dev build?
And if it still doesn't work, could you shoot a video?

**Comment by MrKippo** [comment]
That seemed to fix it!
