### ISSUE TITLE
Disable or Enable Individual Quests

### ISSUE THREAD

**Issue by marvinej** [SkytAsul/BeautyQuests#16]
**Describe the solution you'd like**
I would like to be able to disable and enable quests so that i can set them up and players can't do them when im not done making them. This should be an administrative permission and the quest should still be editable by the admin when its disabled.

**Comment by SkytAsul** [comment]
Yep why not ? It is not hard to set up.

**Comment by SkytAsul** [comment]
Why not setting up a permission requirement where only operators can use it ?
