### ISSUE TITLE
The quest description can have multiple lines

### ISSUE THREAD

**Issue by XiZhang233** [SkytAsul/BeautyQuests#160]
When I use the plugin, I found that the quest description has only one line and cannot be branched
It’s not good from a beautiful or practical point of view
Can you add a function that can describe multiple lines?

**Comment by XiZhang233** [comment]
If you already have this feature, please tell me how to use this feature.
Thank you very much!

**Comment by SkytAsul** [comment]
You can use the `{nl}` placeholder anywhere you want to break a line!

**Comment by DisguisedPixels** [comment]
> You can use the {nl} placeholder anywhere you want to break a line!

I am using this, but i get a description like this: 

![image](https://user-images.githubusercontent.com/72760989/115966326-aa3b8380-a4f2-11eb-97e0-4d7040bd3c77.png)

description: '§9[Craft]§7§l > §9[Mine]§7§l > §9[Craft]{nl}§cRequires §6§lWarm Welcome{nl}§7Reward: §2Green Gift x1§7, §5Baked Potato x3'

**Comment by SkytAsul** [comment]
Has been fixed when revamped quest description!
