### ISSUE TITLE
Add support for mythicmobs skills

### ISSUE THREAD

**Issue by disqetow** [SkytAsul/BeautyQuests#161]
If player using mythicmobs skill to kill mobs, it will not count to kill mobs quest
This plugin only detect mobs kill by player hit them.

Can you add support mythicmobs skills?

**Comment by EnderGriefeur99** [comment]
it's a limitation of mythicmobs we check the mythicmobs event

**Comment by disqetow** [comment]
> it's a limitation of mythicmobs we check the mythicmobs death event

So this is impossible right?

**Comment by EnderGriefeur99** [comment]
yes

**Comment by EnderGriefeur99** [comment]
you need to pm the mythicmobs dev

**Comment by disqetow** [comment]
> you need to pm the mythicmobs dev

ok, thank you.
