### ISSUE TITLE
command reward

### ISSUE THREAD

**Issue by zyte123** [SkytAsul/BeautyQuests#162]
Hi I was wondering is there a way so that I can make commands from quests a perma reward for example I want someone to finish 
a quest but after that they have the command forever and they do not have to do the same quest again or another

**Comment by sunalsun** [comment]
You can execute a command from your perms plugin to give permission to a player i.e. LuckPerms.
Example would be to execute a command after the quest is done to something like '/lp user {PLAYER} permission set <custom.permission>'. Now the player would have the permission node executed from the quest.
You can use a plugin like MyCommands to setup a custom command and custom permission for that command so only the players with the permission will be able to use that command.
Hope this helps.

**Comment by SkytAsul** [comment]
^ this answered.
