### ISSUE TITLE
npc 

### ISSUE THREAD

**Issue by zyte123** [SkytAsul/BeautyQuests#163]
hi is there a way to edit the npc that I have set to one of my quests I try but it just brings me to the quest menu maybe I have to change the name from the citizens plugin could you give me the command

**Comment by EnderGriefeur99** [comment]
/npc name <newname>, else i coded this plugin to edit all settings for your citizens https://www.spigotmc.org/resources/citizensgui.74383/

**Comment by SkytAsul** [comment]
`/npc sel` while looking at the NPC, then `/npc rename <new name>`.
