### ISSUE TITLE
Scoreboard Infos

### ISSUE THREAD

**Issue by CraftCityHD** [SkytAsul/BeautyQuests#164]
Ist es möglich das Scoreboard so anzupassen das man den aktuellen Fortschritt der Quest anzeigen lassen kann. Z.b Töte 10 Kühe und im Scoreboard steht 5/10 Kühe. Das wäre das was mit fehlt. Sonst ist alles top gemacht.

**Comment by SkytAsul** [comment]
Sorry, could you please explain yourself in English please?

**Comment by Deazzyfeat** [comment]
Is it possible to adjust the scoreboard so that you can display the current progress of the quest? As an example: Kill 10 cows and the scoreboard shows 5/10 cows. I'm missing that. The plugin is well done

**Comment by SkytAsul** [comment]
Customize in config.yml the line `stageDescriptionItemsSplit.amountFormat` as you wish. In your case it would probably be `{1}/{2}`.
