### ISSUE TITLE
When pressing the quests it is not starting.

### ISSUE THREAD

**Issue by Shixpy** [SkytAsul/BeautyQuests#168]
When a player clicks to the quest it is not starting and plugin doesn't sending any errors.

Plugin is not sending any errors.

BeautyQuests version: 0.18.5
Game version: 1.16.5
Server version: 1.16.5
Server type (e.i. PaperSpigot): Tuinty
Are you using a protocol hack (like ViaVersion)?
Yes

**Comment by EnderGriefeur99** [comment]
your citizens tells you a thing like hi i'm npc ?

**Comment by aidenszolosi** [comment]
I second this bug, don't know the fix and I use 1.17

**Comment by SkytAsul** [comment]
> I second this bug, don't know the fix and I use 1.17

Is your NPC telling you something? Or really nothing appears in the chat? And are there errors in console, at startup or during runtime?
