### ISSUE TITLE
An objective placeholder

### ISSUE THREAD

**Issue by jppabs115** [SkytAsul/BeautyQuests#174]
**Is your feature request related to a problem?**
Currently the placeholder %beautyquests_started_ordered% has a quest name and I wanted to put the placeholder on my own made scoreboard. But the placeholder is just too long because of the quest name. There is also %beautyquests_advancement_[id]% but it only gives the objective of a specific quest.

**Describe a possible solution**
A similar placeholder but only gives the objective of the quest in order.

**Comment by SkytAsul** [comment]
%beautyquests_started_ordered_1% for the name and %beautyquests_started_ordered_2% and _3... for the objective, split into 30-characters long lines.
