### ISSUE TITLE
[suggestion] option to force a quest showing in npc gui even when player does not meet requirement

### ISSUE THREAD

**Issue by hkkongou** [SkytAsul/BeautyQuests#176]
**Is your feature request related to a problem?**
I got a very big concern if quest does not show up when players does not meet requirement. Currently, bq quest only show up when player meet the quest requirement , the problem is that, if the player does not know the requirement , he will never know that the npc he/she is clicking have alot of quest, or there are many quest can be unlock after finish one parent quest.

I know it is possible to view all of the quest using /bq command, then all quest can be pop up. But for me, i would rather choose not to show quest in /bq command, only allow players to right click certain npc, use the gui to take a quest, so this would be important to me

**Describe a possible solution**
add a option to force a quest show in quest gui, so that the player can view that there are many quest can be taken from this npc, if the player does not meet all requirement, the bq system will tell the player what requirement does not match.

**Describe alternatives you've considered (optional)**
an small counter below the npc gui, show that there are totally xxx number of quest can be taken from an npc, how many quest cannot be taken due to requirement not match.

however this have to be done after #175  as the GUI need to be fixed to do these all kind of extra functions

**Additional context (optional)**

(FR: Si vous êtes plus facilement compréhensible en français, écrivez dans cette langue car il s'agit de ma langue natale)

**Comment by SkytAsul** [comment]
Forgot to close this issue but that's present in the plugin for some time now.
