### ISSUE TITLE
[bug] quests in progress preventing npc to open npc gui

### ISSUE THREAD

**Issue by hkkongou** [SkytAsul/BeautyQuests#177]
**Describe the bug**	
~~hi~~
~~i have 2 npc, named npc A and npc B, npc B have some quest(not important), npc A have 1 quest.~~
~~For npc A, the quest is to give item to npc B, but when i took a quest from npc A, if i click on npc B, i cannot open the npc B gui, it locked on submitting item to npc B.~~

if there is a quest that require give item to an npc, the npc that will take item cannot open its npc gui.

**Reproduction**
make a quest that deliver item to an npc , the start npc is also the npc that receive delivery. Also make more quest on the same npc. When player took a quest that give item to this npc, the npc gui cannot be open, because the quest is forcing player to give item before open gui

**Screenshots, error messages**
cannot open NPC B(on the right) which have other quest as a quest from NPC A is asking player to submit item to npc B
![image](https://user-images.githubusercontent.com/61608872/123509061-fc8d5200-d6a5-11eb-8959-255377a11c52.png)

**Software**
BeautyQuests version: beautyquests-0.19.0-SNAPSHOT#228
Game version:1.16.5
Server version:purpurclip-1.16.5-1125
Server type (e.i. PaperSpigot): purpur
Are you using a protocol hack (like ViaVersion)? no

**Additional context (optional)**
No : (

(FR: Si vous êtes plus facilement compréhensible en français, écrivez dans cette langue car il s'agit de ma langue natale)

**Comment by SkytAsul** [comment]
Has been fixed when revamped click handling a while ago, I forgot to close this issue.
