### ISSUE TITLE
Races of thana permissions arent accepted by beatyquest

### ISSUE THREAD

**Issue by Svastojed** [SkytAsul/BeautyQuests#183]
**Describe the bug**	
beatyquest doesnt accept races of thana perms.

**Reproduction**
Steps to reproduce the behavior. (If not already explained above.)

**Screenshots, error messages**
Are there error messages in the console or in the chat?

**Software**
BeautyQuests version:
Game version:
Server version:
Server type (e.i. PaperSpigot):
Are you using a protocol hack (like ViaVersion)?

**Additional context (optional)**

(FR: Si vous êtes plus facilement compréhensible en français, écrivez dans cette langue car il s'agit de ma langue natale)

**Comment by EnderGriefeur99** [comment]
can you join the discord to check you issue ^^ ? https://discord.gg/H8fXrkD

**Comment by SkytAsul** [comment]
The issue is not correctly filled.
