### ISSUE TITLE
Quest Pool and Branches

### ISSUE THREAD

**Issue by GrannySue20** [SkytAsul/BeautyQuests#184]
Just wondering what both of these are.  Any tips?

I've created 45 quests so far for our new server and love the plug in but if I could make use of more of the features that would be great!

Thank you

GrannySue

**Comment by SkytAsul** [comment]
I've made a tutorial (in french but you can look at the pictures) for branches: https://youtu.be/LxK1evfv2Gk

Quest pools are a way to group quests and give one (or more) quest(s) of the group randomly to a player through a NPC.

**Comment by GrannySue20** [comment]
Thanks
I like both of those ideas!  I’ll keep going as I am for now but I like the idea of the pools!
Many thanks
Sue


Sent from Yahoo Mail for iPhone


On Saturday, July 24, 2021, 3:16 pm, SkytAsul ***@***.***> wrote:




I've made a tutorial (in french but you can look at the pictures) for branches: https://youtu.be/LxK1evfv2Gk

Quest pools are a way to group quests and give one (or more) quest(s) of the group randomly to a player through a NPC.

**Comment by GrannySue20** [comment]
Still struggling to understand branches.  Our server has now launched with over 40 quests for players.  We’re hoping players will enjoy them.  The quests earn players money to buy land for their survival builds.

We’d love you to pop on sometime and see how we’ve used your brilliant plug in!

Server name:
Isoverse.net

Then join the survival realm.

Our players are enjoying the quests!

Many thanks.

GrannySue. (Admin, quest writer and survival spawn builder)

**Comment by SkytAsul** [comment]
Do you have an idea of a quest with branches you'd like me to explain you how to create?

**Comment by SkytAsul** [comment]
I created 2 tutorials in english
Pools: https://youtu.be/phV8CECGMA0
Branches: https://youtu.be/baT2lb_x_Eg

**Comment by GrannySue20** [comment]
Thank you so much for these!
We want to extend our quest area and I feel adding both of these will add extra to the feel of the game for our players.
Many thanks
Sue
    On Monday, 17 January 2022, 18:03:40 GMT, SkytAsul ***@***.***> wrote:  
 
 


I created 2 tutorials in english
Pools: https://youtu.be/phV8CECGMA0
Branches: https://youtu.be/baT2lb_x_Eg

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
