### ISSUE TITLE
Hide Quest Start Messages

### ISSUE THREAD

**Issue by CoderBoyo** [SkytAsul/BeautyQuests#186]
**Is your feature request related to a problem?**
I start the quests when a player joins a server and the players chat is flooded with start messages.

**Describe a possible solution**
Add a option to the api to start a quest without a message.

**Comment by SkytAsul** [comment]
This has been added as `Quest#start(Player p, boolean silently)` in the [dev build #235](https://ci.codemc.io/job/SkytAsul/job/BeautyQuests/235/)
Thanks for the idea ;-)

**Comment by CoderBoyo** [comment]
Thanks for the quick response! Helps a lot.
