### ISSUE TITLE
Want to to change one thing !

### ISSUE THREAD

**Issue by NickThuan** [SkytAsul/BeautyQuests#189]
I want to change one thing:
My mythicmobs mob example:
H1:
Type: Pig
Display: '&dSuper Pig &7[Lv.1]'
When accepting the quest it will say ' [Quests] You must kill H1'
Why not the mob's display?
'[Quest] You must kill &dSuper Pig &7[Lv.1]'
That will make it easier for players to understand!

**Comment by SkytAsul** [comment]
Haven't seen this issue before. There is a feature to add a custom name for mobs.
