### ISSUE TITLE
Description des étapes dans le menu /quests

### ISSUE THREAD

**Issue by Jeremylo1** [SkytAsul/BeautyQuests#190]
**Describe the bug**	
Dans le menu des quêtes en cours  "/quests", la description des quêtés ne prend pas en compte les code couleurs Minecarft "&l &c" contrairement aux scoreboards.

**Reproduction**
Vous avez juste a créer une quête avec une description d'étape en couleur.
Exemple : "Tuer &5deux &fgros &5lapins &fdans la foret."

**Screenshots, error messages**
![image](https://user-images.githubusercontent.com/11772547/129136359-c0d5adf5-30d1-4e4d-950a-5fe4897ea0b0.png)

**Software**
BeautyQuests version : 0.19.0_BUILD237
Game version: 1.17.1
Purpur version : git-Purpur-1327 (MC: 1.17.1)
Server type (e.i. PaperSpigot): Purpur

**Comment by SkytAsul** [comment]
C'est probablement car tu as modifié le texte dans le fichier YML de la quête. Il faut utiliser le charactère `§` et non `&` quand tu modifies un fichier.
