### ISSUE TITLE
Sous Commandes sans permissions

### ISSUE THREAD

**Issue by Jeremylo1** [SkytAsul/BeautyQuests#191]
**Describe the bug**	
Certaines commandes sont proposé aux joueur n'ayant pourtant pas la permission. Par exemple si un joueur a seulement la permission "beautyquests.command" et "beautyquests.command.help" il auras quand même accès aux commandes "/quests exiteditor" "/quests reopeninventory" et "/quests checkpoint"

**Reproduction**
Ajouter des permissions n'ayant aucun rapport avec les 3 sous commandes précédentes et voir que les sous commandes en questions sont quand même proposé aux joueurs.

**Screenshots, error messages**
![image](https://user-images.githubusercontent.com/11772547/129136844-4611cba1-05a2-4b0a-b064-e9f73864622f.png)

Software
BeautyQuests version : 0.19.0_BUILD237
Game version: 1.17.1
Purpur version : git-Purpur-1327 (MC: 1.17.1)
Server type (e.i. PaperSpigot): Purpur

**Comment by SkytAsul** [comment]
Close with https://github.com/SkytAsul/BeautyQuests/commit/11d6e8188a05ecd15a4068a1bb80003bacbe44b5
