### ISSUE TITLE
[suggestion] Particules pour l'option Location

### ISSUE THREAD

**Issue by Jeremylo1** [SkytAsul/BeautyQuests#193]
Avoir la possibilité d'activer ou non des effets de particules pour l'action "Location" comme pour l'option "Talk" sans forcément cacher la scoreboard. Car il peut être plus agréable pour un joueur de voir clairement la zone directement dans le jeu sans passer par le f3. Si l'emplacement est proche du joueur évidemment. 

Afficher des particules soit sur le bloc en lui-même, soit dans le rayon autour du bloc.

Cela pourrait être utile pour une quête d'introduction qui indiquerait au joueur de suivre les "lumières au sol"

**Comment by SkytAsul** [comment]
C'est possible avec l'Expansion depuis un moment (j'avais oublié de fermer ce ticket).
