### ISSUE TITLE
Custom holograms accumulate when reloading plugin

### ISSUE THREAD

**Issue by AaronPBCraft** [SkytAsul/BeautyQuests#194]
**Describe the bug**	
When reloading with `/quests reload`, a new custom hologram is generated above the NPC, but the old one is still there being accumulated.

**Reproduction**
1. Create a quest with NPC activation and set a hologram with custom text and launch item.
2. Reload plugin 3-4 times with `/quests reload`.

The issue can be fixed reloading Citizens and BeautyQuests or reloading the server.

**Screenshots, error messages**
![image](https://user-images.githubusercontent.com/70075352/130108030-5e279c3d-3799-49d0-a565-03c399734670.png)
There are no error messages in the console or in the chat.

**Software**
Involved plugs versions:
- BeautyQuests v0.18.5
- Citizens v2.0.28-SNAPSHOT (build 2357)
- HolographicDisplays v2.4.9

Game version: 1.17.1
Server version: Java 16 (Java HotSpot(TM) 64-Bit Server VM 16.0.1+9-24) Host: Windows 10 10.0 (amd64)
Server type (e.i. PaperSpigot): purpur-1.17.1-1291
Are you using a protocol hack (like ViaVersion)? No

**Comment by EnderGriefeur99** [comment]
never BeautyQuests reload, btw for 1.17.1 use beautyquests 0.19

**Comment by AaronPBCraft** [comment]
@EnderGriefeur99 thanks for your quick reply!
Bug remains using v0.19 but I understand that if I want to modify something in config, I have to reload the entire server.
Is there a way to avoid this?

**Comment by EnderGriefeur99** [comment]
restart the server never reload
