### ISSUE TITLE
Error when trying to get into quest rewards

### ISSUE THREAD

**Issue by Julimaxx** [SkytAsul/BeautyQuests#198]
**Describe the bug**
Hello and I hope you read soon,
I'm using the software Mohist to combine mods and plugins in the same server. The error occurs when I'm going to put a reward
in "end reward" and then selecting a red stained glass. In console throws a lot of issues, and visually doesn't appear any option  to choose a type of reward.
Best regards.

**Reproduction**
Named before.

**Screenshots, error messages**
07.09 21:24:59 [Server] WARN java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
07.09 21:24:59 [Server] WARN at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
07.09 21:24:59 [Server] WARN at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source)
07.09 21:24:59 [Server] WARN at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)
07.09 21:24:59 [Server] WARN at java.base/java.util.Objects.checkIndex(Unknown Source)
07.09 21:24:59 [Server] WARN at java.base/java.util.ArrayList.get(Unknown Source)
07.09 21:24:59 [Server] WARN at fr.skytasul.quests.gui.templates.ListGUI.onClick(ListGUI.java:88)
07.09 21:24:59 [Server] WARN at fr.skytasul.quests.gui.Inventories.onClick(Inventories.java:74)
07.09 21:24:59 [Server] WARN at fr.skytasul.quests.QuestsListener.onClick(QuestsListener.java:98)
07.09 21:24:59 [Server] WARN at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
07.09 21:24:59 [Server] WARN at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
07.09 21:24:59 [Server] WARN at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
07.09 21:24:59 [Server] WARN at java.base/java.lang.reflect.Method.invoke(Unknown Source)
07.09 21:24:59 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:303)
07.09 21:24:59 [Server] WARN at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
07.09 21:24:59 [Server] WARN at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
07.09 21:24:59 [Server] WARN at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:588)
07.09 21:24:59 [Server] WARN at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:573)
07.09 21:24:59 [Server] WARN at net.minecraft.network.play.ServerPlayNetHandler.func_147351_a(ServerPlayNetHandler.java:2302)
07.09 21:24:59 [Server] WARN at net.minecraft.network.play.client.CClickWindowPacket.func_148833_a(CClickWindowPacket.java:34)
07.09 21:24:59 [Server] WARN at net.minecraft.network.play.client.CClickWindowPacket.func_148833_a(CClickWindowPacket.java:12)
07.09 21:24:59 [Server] WARN at net.minecraft.network.PacketThreadUtil.lambda$ensureRunningOnSameThread$0(PacketThreadUtil.java:26)
07.09 21:24:59 [Server] WARN at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18)
07.09 21:24:59 [Server] WARN at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:153)
07.09 21:24:59 [Server] WARN at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
07.09 21:24:59 [Server] WARN at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:881)
07.09 21:24:59 [Server] WARN at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:177)
07.09 21:24:59 [Server] WARN at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:126)
07.09 21:24:59 [Server] WARN at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:864)
07.09 21:24:59 [Server] WARN at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:858)
07.09 21:24:59 [Server] WARN at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:136)
07.09 21:24:59 [Server] WARN at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:844)
07.09 21:24:59 [Server] WARN at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:764)
07.09 21:24:59 [Server] WARN at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:270)
07.09 21:24:59 [Server] WARN at java.base/java.lang.Thread.run(Unknown Source)

**Software**
BeautyQuests version: 0.18.5 (Last one right now)
Game version: 1.16.5
Server version: 1.16.5
Server type (e.i. PaperSpigot): Mohist
Are you using a protocol hack (like ViaVersion)? No

**Additional context (optional)**
The thing is that you can continue doing quests, but without a reward are very useless.

(FR: Si vous êtes plus facilement compréhensible en français, écrivez dans cette langue car il s'agit de ma langue natale)

**Comment by EnderGriefeur99** [comment]
We don't support mohist so try to use the 0.19 version, or use a plugin designed for mohist
