### ISSUE TITLE
Player starts a quest with a item

### ISSUE THREAD

**Issue by ianguuima** [SkytAsul/BeautyQuests#20]
**Is your feature request related to a problem? Please describe.**
No, isn't.

**Describe the solution you'd like**
I'd like that have a option that I can create a start reward, like when the player starts a quest he gain a item.

**Comment by SkytAsul** [comment]
Well so, reward are directly gived when the quest starts ?

**Comment by ianguuima** [comment]
Yes, it'll be a good idea.

example: A miner needs that the player break some blocks, then on the quest starts the miner I'll give his pickaxe or sometinhg like that.

**Comment by SkytAsul** [comment]
Okay, will be in the next version !

**Comment by SkytAsul** [comment]
Preview version on my Discord server
