### ISSUE TITLE
Task target language

### ISSUE THREAD

**Issue by Wuip** [SkytAsul/BeautyQuests#202]
Can the author add language options to the development version, just like in the official version 0.18.5? I really need it
![QQ截图20211128213407](https://user-images.githubusercontent.com/95348722/144219696-dcec4b1d-7ab2-4dfc-97e8-2c36de8f0e32.png)

**Comment by SkytAsul** [comment]
If you are using latest BQ dev build, you can use `/quests downloadTranslations zh_cn`

**Comment by Wuip** [comment]
thank you for your reply! Is there any other way to download this? After I input it, it prompts Read timed out

**Comment by Wuip** [comment]
> 如果您使用的是最新的 BQ 开发版本，则可以使用`/quests downloadTranslations zh_cn`

thank you for your reply! Is there any other way to download this? After I input it, it prompts Read timed out

**Comment by Wuip** [comment]
> If you are using latest BQ dev build, you can use `/quests downloadTranslations zh_cn`

After the download is successful, I am prompted to go to config.yml to modify the minecraftTranslationsFile option, but the development version does not have this option

**Comment by Wuip** [comment]
> 如果您使用的是最新的 BQ 开发版本，则可以使用 `/quests downloadTranslations zh_cn`

And after I added minecraftTranslationsFile: zh_cn option and restarted the server, the setting will be invalid and return to English

**Comment by SkytAsul** [comment]
Had the file been correctly downloaded into the plugin's folder?

**Comment by Wuip** [comment]
> 文件是否已正确下载到插件的文件夹中？

Yes, it has been downloaded successfully, but it cannot be used without the minecrafttranslationsfile option

**Comment by Wuip** [comment]
> 文件是否已正确下载到插件的文件夹中？

Yes, it has been downloaded successfully, but it cannot be used without the minecrafttranslationsfile option

**Comment by SkytAsul** [comment]
Try this:
- stop your server
- put the option `minecraftTranslationsFile: zh_cn.json` in *config.yml*
- start the server

**Comment by Wuip** [comment]
> Try this:
> 
> * stop your server
> * put the option `minecraftTranslationsFile: zh_cn.json` in _config.yml_
> * start the server

This is feasible! However, the minecraft translations file option will disappear after the server is started, and will expire the next time the server is started. The language will return to English

**Comment by Wuip** [comment]
> Try this:
> 
> * stop your server
> * put the option `minecraftTranslationsFile: zh_cn.json` in _config.yml_
> * start the server

Do this every time you start the server, isn't it a little troublesome

**Comment by SkytAsul** [comment]
Oh so it works once and then it do not work anymore?

**Comment by Wuip** [comment]
> 哦所以它工作一次然后它不再工作了？

It's like I modified the wrong config file and automatically restored the correct settings

**Comment by SkytAsul** [comment]
It was indeed a bug, I just fixed it in dev build 266. You can download it here: https://ci.codemc.io/job/SkytAsul/job/BeautyQuests/

**Comment by Wuip** [comment]
> 这确实是一个错误，我只是在 dev build 266 中修复了它。你可以在这里下载它：[https](https://ci.codemc.io/job/SkytAsul/job/BeautyQuests/) : [//ci.codemc.io/job/SkytAsul/job/BeautyQuests/](https://ci.codemc.io/job/SkytAsul/job/BeautyQuests/)

Thanks!
