### ISSUE TITLE
Show waypoints on the set "go to location" locations

### ISSUE THREAD

**Issue by captainion2119** [SkytAsul/BeautyQuests#204]
**Is your feature request related to a problem?** 
It's a problem on my server when there are players that are new to Minecraft and have no knowledge of how to use the coordinates so it's tough for them to understand and navigate between waypoints of the quests when the quest stage is a "Go to location" stage.

**Describe a possible solution**
There is an option of purchasing the "GPS plugin", I am aware of that, but that isn't an option due to the currently low funds, and the plugin is kinda annoying, So I request an addition of a small particle effect or a floating emerald sprite above the set locations like the particles above NPCs.

**Describe alternatives you've considered:**
Just one, but this is low priority, so it would be awesome if there was a simpler GUI for managing branching quests.

**Comment by captainion2119** [comment]
I noticed you have already added this feature request on the to-do list, apologies for that, I noticed a tiny tad late.
The card: https://github.com/SkytAsul/BeautyQuests/projects/1#card-58151879

**Comment by SkytAsul** [comment]
It is planned for a future update ^^

**Comment by SkytAsul** [comment]
Coming back to this years later: I have created the Expansion for this, by adding lot of trackers in it :) https://www.spigotmc.org/resources/beautyquests-expansion-early-access.104701/
