### ISSUE TITLE
Report some problems you find

### ISSUE THREAD

**Issue by eyesonme1212** [SkytAsul/BeautyQuests#206]
First, my curiosity. I want to reset a specific player's quest
I'll also tell you the problems I found.
When deleting a quest, the ID is not deleted.
If you delete ID 4, the next quest will be created as 5 instead of 4

**Comment by SkytAsul** [comment]
> First, my curiosity. I want to reset a specific player's quest
You can use the command `/quests resetPlayerQuest <playername> <quest id>`

> When deleting a quest, the ID is not deleted.
> If you delete ID 4, the next quest will be created as 5 instead of 4
That's intended behavior. This way, if there was commands in external plugins associated with a specific quest via its ID (to manually start the quest or do some management), this will not produce unexpected results by affecting a new quest.

**Comment by eyesonme1212** [comment]
thx!!!
