### ISSUE TITLE
Can't Take The Quest

### ISSUE THREAD

**Issue by A212H212** [SkytAsul/BeautyQuests#209]
Why i can't take the quest? I have clicked on it very much times but i can't get the Quest.
![image](https://user-images.githubusercontent.com/96674747/152632277-b05c37ed-d3fa-4e2a-8377-62827d3b8b39.png)
![image](https://user-images.githubusercontent.com/96674747/152632291-eea6979b-6fc5-42f7-9ec5-a770f96e98be.png)
![image](https://user-images.githubusercontent.com/96674747/152632298-62f4e25f-c38a-461c-9ab4-5a7b64225ea0.png)

**Software**
BeautyQuests version: beautyquests-0.19.0-SNAPSHOT.jar
Game version: 1.16.5
Server version: 1.16.5
Server type (e.i. PaperSpigot): Paper
Are you using a protocol hack (like ViaVersion)?
Im using ViaVersion

**Comment by SkytAsul** [comment]
Have you at least enabled the "startable from GUI" quest option in the edition GUI?

**Comment by SkytAsul** [comment]
Hello? Is this still an issue?

**Comment by captainion2119** [comment]
@A212H212 do you have any permissions plugin on your server?

**Comment by SkytAsul** [comment]
I assume this as fixed.
