### ISSUE TITLE
Update to 1.18.1 causes playes can't start quest

### ISSUE THREAD

**Issue by Lucianoobxd** [SkytAsul/BeautyQuests#212]
When i updated My server to 1.18.1 players can't take quest unless they are OP

They can't take they quest, it's really annoying because i tried a Lot OF permissions n updating My plugins!

I want yo know how to know what is my problem

**Software**
BeautyQuests version: 0.268
Game version: 1.18.1
Server version: Paper lastest 1.18.1
Server type (e.i. PaperSpigot): Paper

I tried snapshots version n problem still there.

**Comment by SkytAsul** [comment]
Update to latest version published today, and tell my again.

**Comment by Lucianoobxd** [comment]
I tried backup quest, nothing works maybe luckyperms 1.18 got problemas when hook the plugin premissions but when i got deop i cant take missions

**Comment by Lucianoobxd** [comment]
I cant interact with the NPC when im deop, n cant accept missions i tried all the citizens perms n nothing works please dude need help i  got like 6 months developing this

**Comment by captainion2119** [comment]
@Lucianoobxd If you are using Luckperms (latest version) make sure you have given the default user group "beautyquests.start" permission node, This was an error on my server too, but seems there is a permission node for that.

**Comment by Lucianoobxd** [comment]
Just tried that my dude, but the problem still there, but thanks for the weight tip of the permissions 👍

**Comment by captainion2119** [comment]
ooh, cool 👍

**Comment by SkytAsul** [comment]
We eventually found out that the plugin in cause was LibsDigsuise.
