### ISSUE TITLE
Problems with Questpools Holograms and "bring back item" quests

### ISSUE THREAD

**Issue by xmorose** [SkytAsul/BeautyQuests#216]
**Describe the bug**	
"You can accept a new quest" Hologram shows even if you cant accept a new quest. Im not sure whether this is a problem because of the item quests, but this is a bit weird
Item quests: If you have multiple "bring back x item" quests in a questpool given out, players cant just bring any item back, theres a fixed order for the quests. If i have 2 quests, bring back diamonds and iron, i cant just bring back iron, and then diamonds, i have to bring back exactly what the NPC says - Would be great if it could just be any item

Edit: The hologram just dissapeared after i completed all quests the npc gave to me

**Reproduction**
Create NPC with a questpool that contains multiple quests, including multiple "bring back x item" quests, accept quests, watch

**Screenshots, error messages**
![Screenshot_2](https://user-images.githubusercontent.com/53750990/160481239-3f7c90fc-275a-4f04-b0ea-d1fa9c7d1008.png)

**Software**
BeautyQuests version: 0.19.1_BUILD287
Game version: 1.18.1
Server version: 1.18.1
Server type (e.i. PaperSpigot): Paper 

(FR: Si vous êtes plus facilement compréhensible en français, écrivez dans cette langue car il s'agit de ma langue natale)

**Comment by SkytAsul** [comment]
Please split your issue into two separate issues, as the "items" thing is not related to the pool issue.
Also, please try to reproduce the bug without any "bring back items" stage, to see if it has something to do with it.

**Comment by SkytAsul** [comment]
Please try with [build 300](https://ci.codemc.io/job/SkytAsul/job/BeautyQuests/300/artifact/target/beautyquests-0.19.2-SNAPSHOT.jar)
