### ISSUE TITLE
"Bring back item" quest bug

### ISSUE THREAD

**Issue by xmorose** [SkytAsul/BeautyQuests#218]
**Describe the bug**	
Item quests: If you have multiple "bring back x item" quests in a questpool given out, players cant just bring any item back, theres a fixed order for the quests. If i have 2 quests, bring back diamonds and iron, i cant just bring back iron, and then diamonds, i have to bring back exactly what the NPC says - Would be great if it could just be any item

**Reproduction**
Give an NPC a pool with multiple "bring back item" quests. You can only give the NPC one item after a specific order, not just any item.

**Screenshots, error messages**
Are there error messages in the console or in the chat?

**Software**
BeautyQuests version: 0.19.1_BUILD287
Game version: 1.18.1
Server version: 1.18.1
Server type (e.i. PaperSpigot): Paper

(FR: Si vous êtes plus facilement compréhensible en français, écrivez dans cette langue car il s'agit de ma langue natale)

**Comment by SkytAsul** [comment]
Please try with [build 300](https://ci.codemc.io/job/SkytAsul/job/BeautyQuests/300/artifact/target/beautyquests-0.19.2-SNAPSHOT.jar)
