### ISSUE TITLE
Can't find player with this name! (kill -> null) /// executed command how to trigger player ??

### ISSUE THREAD

**Issue by SoloTHx** [SkytAsul/BeautyQuests#221]
**Describe the bug**	
executed command in rewards // i don't know how to  trigger player ??
example: i wanna run console command to kill the player who completed the quest
and im put this on executed command = kill %player_name% (and other like this%user%/%player%/{player}) and its say in console " Can't find player with this name! (kill -> null) "

HOW TO TRIGGER PLAYERRR PLS

**Software**
BeautyQuests version: 0.19.2
Game version: 1.18.2
Server version: 1.17.1
Server type (e.i. PaperSpigot): Paper
Are you using a protocol hack (like ViaVersion)? yes i use viaversion ( last version )

**Comment by SoloTHx** [comment]
Now I know why

I'm sorry, I'm a fool myself.

Because I wrote a non-capital {player}, it has to be capitalized like this {PLAYER}.

I'm sorry, it's written on the wiki, but I didn't read it. I'm stupid

**Comment by SkytAsul** [comment]
That's alright, it's good if you found the solution :)
