### ISSUE TITLE
[BUG] Can't create quest with music disc (otherside)

### ISSUE THREAD

**Issue by HeliosMY** [SkytAsul/BeautyQuests#224]
**Describe the bug**	
Can't put music disc otherside in bring back items quests.

**Reproduction**
Create a stage (bring back items) and put music disc (otherside), fill up quest's name and click create, error is occurred.

**Screenshots, error messages**
> 23.05 17:03:48 [Server] ERROR [BeautyQuests] An error occurred wheh creating branch from GUI.
> 23.05 17:03:48 [Server] INFO java.lang.IllegalArgumentException: Unsupported material from item: MUSIC_DISC_OTHERSIDE (0)
> 23.05 17:03:48 [Server] INFO at fr.skytasul.quests.utils.XMaterial.lambda$matchXMaterial$1(XMaterial.java:2757) ~[beautyquests-0.19.5.jar:?]
> 23.05 17:03:48 [Server] INFO at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
> 23.05 17:03:48 [Server] INFO at fr.skytasul.quests.utils.XMaterial.matchXMaterial(XMaterial.java:2757) ~[beautyquests-0.19.5.jar:?]
> 23.05 17:03:48 [Server] INFO at fr.skytasul.quests.utils.MinecraftNames.getMaterialName(MinecraftNames.java:83) ~[beautyquests-0.19.5.jar:?]
> 23.05 17:03:48 [Server] INFO at fr.skytasul.quests.gui.ItemUtils.getName(ItemUtils.java:288) ~[beautyquests-0.19.5.jar:?]
> 23.05 17:03:48 [Server] INFO at fr.skytasul.quests.utils.Utils.getStringFromItemStack(Utils.java:137) ~[beautyquests-0.19.5.jar:?]
> 23.05 17:03:48 [Server] INFO at fr.skytasul.quests.stages.StageBringBack.<init>(StageBringBack.java:51) ~[beautyquests-0.19.5.jar:?]
> 23.05 17:03:48 [Server] INFO at fr.skytasul.quests.stages.StageBringBack$Creator.createStage(StageBringBack.java:230) ~[beautyquests-0.19.5.jar:?]
> 23.05 17:03:48 [Server] INFO at fr.skytasul.quests.stages.StageBringBack$Creator.createStage(StageBringBack.java:222) ~[beautyquests-0.19.5.jar:?]
> 23.05 17:03:48 [Server] INFO at fr.skytasul.quests.stages.StageNPC$AbstractCreator.finishStage(StageNPC.java:354) ~[beautyquests-0.19.5.jar:?]
> 23.05 17:03:48 [Server] INFO at fr.skytasul.quests.stages.StageNPC$AbstractCreator.finishStage(StageNPC.java:287) ~[beautyquests-0.19.5.jar:?]
> 23.05 17:03:48 [Server] INFO at fr.skytasul.quests.api.stages.StageCreation.finish(StageCreation.java:155) ~[beautyquests-0.19.5.jar:?]
> 23.05 17:03:48 [Server] INFO at fr.skytasul.quests.gui.creation.FinishGUI.loadBranch(FinishGUI.java:256) ~[beautyquests-0.19.5.jar:?]
> 23.05 17:03:48 [Server] INFO at fr.skytasul.quests.gui.creation.FinishGUI.finish(FinishGUI.java:203) ~[beautyquests-0.19.5.jar:?]
> 23.05 17:03:48 [Server] INFO at fr.skytasul.quests.gui.creation.FinishGUI.access$200(FinishGUI.java:40) ~[beautyquests-0.19.5.jar:?]
> 23.05 17:03:48 [Server] INFO at fr.skytasul.quests.gui.creation.FinishGUI$3.click(FinishGUI.java:138) ~[beautyquests-0.19.5.jar:?]
> 23.05 17:03:48 [Server] INFO at fr.skytasul.quests.gui.creation.FinishGUI.onClick(FinishGUI.java:161) ~[beautyquests-0.19.5.jar:?]
> 23.05 17:03:48 [Server] INFO at fr.skytasul.quests.gui.Inventories.onClick(Inventories.java:78) ~[beautyquests-0.19.5.jar:?]
> 23.05 17:03:48 [Server] INFO at fr.skytasul.quests.QuestsListener.onClick(QuestsListener.java:129) ~[beautyquests-0.19.5.jar:?]
> 23.05 17:03:48 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1365.execute(Unknown Source) ~[?:?]
> 23.05 17:03:48 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
> 23.05 17:03:48 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:git-Purpur-1625]
> 23.05 17:03:48 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
> 23.05 17:03:48 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:671) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
> 23.05 17:03:48 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:2946) ~[?:?]
> 23.05 17:03:48 [Server] INFO at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
> 23.05 17:03:48 [Server] INFO at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
> 23.05 17:03:48 [Server] INFO at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
> 23.05 17:03:48 [Server] INFO at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.18.2.jar:git-Purpur-1625]
> 23.05 17:03:48 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
> 23.05 17:03:48 [Server] INFO at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
> 23.05 17:03:48 [Server] INFO at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1426) ~[purpur-1.18.2.jar:git-Purpur-1625]
> 23.05 17:03:48 [Server] INFO at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[purpur-1.18.2.jar:git-Purpur-1625]
> 23.05 17:03:48 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
> 23.05 17:03:48 [Server] INFO at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1403) ~[purpur-1.18.2.jar:git-Purpur-1625]
> 23.05 17:03:48 [Server] INFO at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1396) ~[purpur-1.18.2.jar:git-Purpur-1625]
> 23.05 17:03:48 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
> 23.05 17:03:48 [Server] INFO at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1374) ~[purpur-1.18.2.jar:git-Purpur-1625]
> 23.05 17:03:48 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1256) ~[purpur-1.18.2.jar:git-Purpur-1625]
> 23.05 17:03:48 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1625]
> 23.05 17:03:48 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Software**
BeautyQuests version: 0.19.5
Game version: 1.18.2
Server version: 1625
Server type (e.i. PaperSpigot): PurpurMC
Are you using a protocol hack (like ViaVersion)? No

**Comment by SkytAsul** [comment]
Thank you for reporting! This is now fixed in 0.19.6.
