### ISSUE TITLE
Added dialogue between NPC and player at the end of the mission

### ISSUE THREAD

**Issue by XiaoYu5530** [SkytAsul/BeautyQuests#225]
This quest plugin is well done, but the dialogue interaction between the NPC and the player seems to be missing at the end of the quest, will it be added in the future?

**Comment by SkytAsul** [comment]
No, as the quest can end without necessarily having a NPC on the last stage. In order to make an "end dialog", you can simply create one last stage with a NPC and put your dialog here.
Feel free to tell me if I have not answered your question correctly.

**Comment by SkytAsul** [comment]
Thanks to you ^^
