### ISSUE TITLE
unsupport MANGROVE_LOG

### ISSUE THREAD

**Issue by disqetow** [SkytAsul/BeautyQuests#227]
**Describe the bug**	
beautyquest didnt support 1.19 new item : MANGROVE_LOG

**Reproduction**
try create MANGROVE_LOG quest

**Screenshots, error messages**
https://pastebin.com/Aa45fvYT

**Software**
BeautyQuests version:
Game version: 1.19
Server version: 1.19
Server type : pufferfish
Are you using a protocol hack (like ViaVersion)? no 

**Additional context (optional)**
cant create MANGROVE_LOG quest

**Comment by SkytAsul** [comment]
This has been fixed in [dev build 318](https://ci.codemc.io/job/SkytAsul/job/BeautyQuests/318/), thanks for reporting!
