### ISSUE TITLE
1.12.2 "/quest reload" issue

### ISSUE THREAD

**Issue by TeQTabanca** [SkytAsul/BeautyQuests#232]
**Describe the bug**	
First of all, I set "enablePrefix: false" in "config.yml" file and set a few places in "en_Us.yml" file according to my language, but nothing changes after using "/quest reload" command. It only changes if I close and open the plugin or Restart the Server.

**Reproduction**
1- Set and save the adjustable locations.
2- Use the command "/quest reload".

**Software**
BeautyQuests version: 0.19.7
Game version: 1.12.2
Server version: CraftBukkit version git-Spigot-79a30d7-f4830a1 (MC: 1.12.2)
Server type (e.i. PaperSpigot): Spigot
Are you using a protocol hack (like ViaVersion)? no I do not use

**Comment by SkytAsul** [comment]
As stated in a message when using the reload command, it is likely to produce bugs and is not recommended. This command is provided for debug purposes and should never be used in a production server.
For memory saving and optimization purpose, the lang file is loaded at startup and will not get updated after the plugin reload.
Hence, this is a won't fix - if you want to reload your changes after editing the config file, restart the server completely.
