### ISSUE TITLE
Automatic start of tasks feature

### ISSUE THREAD

**Issue by TeQTabanca** [SkytAsul/BeautyQuests#233]
**Is your feature request related to a problem?**
Instead of "start automatically on first join" feature, "auto start" feature can be added.

**Describe a possible solution**
First of all, I do repeatable quests. It may be better for players if this feature is added. Because I think it might be better for gamers if it starts automatically instead of starting repeatable missions or normal missions from GUI.

**Comment by TeQTabanca** [comment]
2- In addition, it would be good if the ability to refresh the GUI per second is added.

**Comment by SkytAsul** [comment]
Please explain how exactly does an "auto start" option differs from the existing "start on first join" option.

**Comment by TeQTabanca** [comment]
> Please explain how exactly does an "auto start" option differs from the existing "start on first join" option.

The autostart feature is that the players take the quest automatically. That is, it automatically goes to the "Quests in progress" section instead of clicking through the GUI.

**Comment by SkytAsul** [comment]
Well, that's basically what is doing the "start on first join" option.

**Comment by TeQTabanca** [comment]
but it can be useful for repeatable tasks.

**Comment by TeQTabanca** [comment]
For example:
You finished the repeatable task and when it expires wouldn't it be better if it started automatically instead of logging back in?

**Comment by SkytAsul** [comment]
Just add a delayed command reward which runs the "quests start" command and voilà.

**Comment by TeQTabanca** [comment]
Well, if the player leaves the game after doing that task and comes back a few hours later, the task will not start automatically. Is there a solution to it? In fact, the "start automatically on first join" feature only works when you join for the first time. I mean, your solution fits, but my proposed feature makes more sense.
