### ISSUE TITLE
Scoredboard

### ISSUE THREAD

**Issue by Ju4nMarin** [SkytAsul/BeautyQuests#235]
Plugin Scoreboard (animatedsb) disappears after completing or canceling a Quests, (with Quests scoreboard enabled)

![image](https://user-images.githubusercontent.com/80414695/181159984-de5566d3-5a72-434d-a72a-6c418b235476.png)
![image](https://user-images.githubusercontent.com/80414695/181160040-7d6747d2-f264-4696-b78c-b7e9bd621843.png)

**Comment by SkytAsul** [comment]
You cannot use different scoreboards. If you want to keep using animatedsb, then disable BeautyQuests scoreboard by setting the `scoreboards` option to `false` in config.yml.

**Comment by Ju4nMarin** [comment]
I can solved with > animatedsb switch defaultscoreboard {PLAYER}
