### ISSUE TITLE
Duplication Glitch

### ISSUE THREAD

**Issue by Galakto0r** [SkytAsul/BeautyQuests#236]
**Describe the bug**	
Quand on prend une quête dont l'objectif est de fabriquer des pelles en fer dans la table de craft par exemple, on peut spam clic droit sur le résultat de la table de craft,
on complète l'objectif sans utiliser les compos.

**Reproduction**
Faire une quête toute simple où il faut fabriquer 15 pelles ou haches en fer, mettre les composants dans l'établi
et spam clic droit sur l'item en question à craft

**Screenshots, error messages**
[https://youtu.be/5B0yaWe0CpE](https://youtu.be/5B0yaWe0CpE) (**Regarder le scoreboard**)

**Software**
BeautyQuests version:beautyquests-0.19.7
Game version: 1.19
Server version: 1.19
Server type (e.i. PaperSpigot): Pufferfish
Are you using a protocol hack (like ViaVersion)? Nop

**Comment by SkytAsul** [comment]
Fixed in 0.20
