### ISSUE TITLE
Beautyquests loading before Citizens

### ISSUE THREAD

**Issue by SykoUSS** [SkytAsul/BeautyQuests#238]
**Describe the bug**	
Beautyquests loading before Citizens

**Reproduction**
Start a server with snapshot 339 BQ and citizens

**Screenshots, error messages**
28.10 03:46:42 [Server] INFO Enabling BeautyQuests v0.20_BUILD339
28.10 03:46:42 [Server] INFO ------------ BeautyQuests ------------
28.10 03:46:42 [Server] INFO Loaded valid Minecraft version 1_19_R1.
28.10 03:46:42 [Server] INFO Loaded language en_US (0.021s)!
28.10 03:46:42 [Server] INFO Loaded start particles: REDSTONE in shape POINT with color R255 G255 B0
28.10 03:46:42 [Server] INFO Loaded talk particles: VILLAGER_HAPPY in shape BAR
28.10 03:46:42 [Server] INFO Loaded next particles: SMOKE_NORMAL in shape SPOT
28.10 03:46:43 [Server] INFO Successfully registered expansion: beautyquests [0.20_BUILD339]
28.10 03:46:43 [Server] INFO Placeholders registered !
28.10 03:46:43 [Server] ERROR No NPC plugin installed - please install Citizens or znpcs
28.10 03:46:43 [Server] ERROR This is a fatal error. Now disabling.

**Software**
BeautyQuests version:
Game version:1.19.2
Server version: Paper-245
Server type: Paper
Are you using a protocol hack (like ViaVersion)? Yes

**Comment by SykoUSS** [comment]
I think this is caused by an eco plugin I added that is changing enable order. Is there a way to fix this?

**Comment by SkytAsul** [comment]
Fixed with the eco plugin
