### ISSUE TITLE
Message with ID x not exist

### ISSUE THREAD

**Issue by Ghost-chu** [SkytAsul/BeautyQuests#25]
**Describe the bug**
When I remove a message by ID, it will report exception,
**To Reproduce**
1.Set Quests dialog
2.remove 1 and 2
3.Throw erros when accepting quests
**Expected behavior**

**Screenshots, errors**
Is there stacktraces in the console ?
![image](https://user-images.githubusercontent.com/30802565/49270624-2a399c80-f4a5-11e8-9a1e-49a6aea9b175.png)
**Softwares (please complete the following information):**
BeautyQuests version (X.X.X, not "latest"), Game version, Server version
Are you using a protocol hack (like ViaVersion) ?
0.12.2 1.13.2 1.13.2 no
**Additional context**

(FR: Si vous êtes plus facilement compréhensible en français, écrivez dans cette langue car il s'agit de ma langue natale)

**Comment by SkytAsul** [comment]
Fixed in latest release
