### ISSUE TITLE
World Blacklist

### ISSUE THREAD

**Issue by EpicJosch** [SkytAsul/BeautyQuests#258]
- A World Blacklist so you cant make progress for quests in specified worlds. For example servers that have Gamemode worlds really need that!

**Comment by SkytAsul** [comment]
You can put a "region requirement" on all your stages with the `__global__` region of your required world.
I don't provide an easier way to do world filtering as having a single server with multiple gamemodes is highly discouraged, you'd better run multiple servers through a proxy.
