### ISSUE TITLE
Request a time zone function

### ISSUE THREAD

**Issue by canicani** [SkytAsul/BeautyQuests#260]
**Is your feature request related to a problem?**
A clear and concise description of what the problem is. E.g. "I'm always frustrated when [...]"

**Describe a possible solution**
A clear and concise description of what you want should be added.

**Describe alternatives you've considered (optional)**

**Additional context (optional)**

(FR: Si vous êtes plus facilement compréhensible en français, écrivez dans cette langue car il s'agit de ma langue natale)

Would it be possible to have the quests start according to standard time?
If not, can the function mentioned above be added?
Your plugin is really useful and I quite appreciate it.

**Comment by SkytAsul** [comment]
1. Please fill the questions, do not put your message at the end.
2. You are mixing up 2 different requests.

Please create two new issues and explain exactly what do you want to get added. I can't understand what a "time zone function" means.
