### ISSUE TITLE
Latest paper version will not wth with BeautyQuests and latest version of Citizens

### ISSUE THREAD

**Issue by darkwisper** [SkytAsul/BeautyQuests#264]
****Describe the bug****	

On the latest version of Paper, the plugin dosen't work!
Here is the console logs:
07.03 22:48:02 [Server] [ERROR] [BeautyQuests] No NPC plugin installed - please install Citizens or znpcs
07.03 22:48:02 [Server] [ERROR] [BeautyQuests] This is a fatal error. Now disabling.

But, we have Citizens as the console reports it as starting, and on the server, NPC's can be seen, but no quests.
07.03 22:47:29 [Server] [INFO] [Citizens] Loading server plugin Citizens v2.0.30-SNAPSHOT (build 2954)
07.03 22:48:27 [Server] [INFO] [Citizens] Enabling Citizens v2.0.30-SNAPSHOT (build 2954)
07.03 22:48:27 [Server] [INFO] [Citizens] Loading external libraries
07.03 22:48:27 [Server] [INFO] [PlaceholderAPI] Successfully registered expansion: citizensplaceholder [1.0.0]
07.03 22:48:27 [Server] [INFO] [Citizens] Loaded economy handling via Vault.

Any updates that could fix this issue?
At this moment, Citizens is at it's latest build, so that's ruled out.

Reproduction

Use the latest Paper version and the latest Citizens2 free build

**Software**
BeautyQuests version: 0.20.0
Game version: 1.19.3
Server version: 1.19.3
Server type (e.i. PaperSpigot): Paper
Are you using a protocol hack (like ViaVersion)?
No idea what this is.

**Additional context (optional)**

EDIT:
The last Paper version that seems to work, is this build (atleast for me):
paper-1.19.3-404

(FR: Si vous êtes plus facilement compréhensible en français, écrivez dans cette langue car il s'agit de ma langue natale)

**Comment by SkytAsul** [comment]
Load order issue. You can see with the timestamps that Citizens is loading
after BeautyQuests, whereas it should load before. You probably have
another plugin fucking up your server load order. I can't help you more,
it's not a problem of BQ or Citizens.

**Comment by darkwisper** [comment]
Sorry to be an annoyance, but I've edited the post, and this is not the issue with paper-1.19.3-404, and any previous version.
If it was another plugin messing with the load order, won't it occur on older versions of paper 1.19.3?
Thanks!

**Comment by SkytAsul** [comment]
No, because Paper precisely changed the plugins loading order algorithm in
a recent 1.19.3 build...

**Comment by SkytAsul** [comment]
No response - seems fixed
