### ISSUE TITLE
Hiding permanently the scoreboard

### ISSUE THREAD

**Issue by rainbowgun15** [SkytAsul/BeautyQuests#272]
J'aimerais pouvoir cacher le scoreboard pour tout les joueurs dans mon server, jutilise deja un plugin qui utilise un scoreboard(project korra) et le scoreboard de beauty quest le cache a chaque fois et ensuite lui de project korra ne revien plus.

Il y a t'il moyen que je puisse le cacher defenitivement? jai essayer /quests scoreboard hide, mais ce n'est pas permanent.

**Comment by SkytAsul** [comment]
Il y a une option pour ça dans le config.yml
https://github.com/SkytAsul/BeautyQuests/blob/aa44729b9826155c8aa1ac7bddca4a268bf7bbfc/core/src/main/resources/config.yml#L37
