### ISSUE TITLE
BeautyQuest is Disabling due to there is no NPC plugin

### ISSUE THREAD

**Issue by RRusmik** [SkytAsul/BeautyQuests#276]
Hello dev 

BeautyQuest is disabling cuz it says there is no NPC plugin But there is znpc which is Working with him because it say download citizens or znpc And The znpc is Being used In the Server 
the server is running on 1.19.3

And this is the console
06 14:11:08 [Server] [ERROR] [BeautyQuests] No NPC plugin installed - please install Citizens or znpcs
27.06 14:11:08 [Server] [ERROR] [BeautyQuests] This is a fatal error. Now disabling.
27.06 14:11:01 [Server] [INFO] [ServersNPC] Enabling ServersNPC v4.2

**Comment by Tuchan** [comment]
If you're using zncps 4.2 either wait for bq update or use znpcs 4.1

You can download the old version from [spigotmc](https://www.spigotmc.org/resources/znpcs.80940/history)

**Comment by RRusmik** [comment]
oh ok thanks
