### ISSUE TITLE
I can't use console command reward of {PLAYER}

### ISSUE THREAD

**Issue by jjuni91236** [SkytAsul/BeautyQuests#28]
Hello guys, I love this plugin.
but, I had problem at use command reward.

The command I use is "level add {PLAYER} xp 100"

However, the space {PLAYER} does not work as a target and works as {PLAYER}.

What should I do?

**Comment by SkytAsul** [comment]
Are you using the latest version of BeautyQuests ?

**Comment by jjuni91236** [comment]
Is it activate at latest version?

**Comment by SkytAsul** [comment]
I fixed a few bugs relative of this yes. Maybe try the latest preview version on my Discord server : https://discord.gg/H8fXrkD
