### ISSUE TITLE
PLAY_TIME

### ISSUE THREAD

**Issue by ZeNsN** [SkytAsul/BeautyQuests#280]
Hi! I really liked the plugin, but there is one problem. I choose PLAY_TIME and quest just doesn't work, it appears at everyone, but when pressed, nothing works

There are no errors, I go to /quest, select the PLAY_TIME task and nothing works

Software
BeautyQuests version: 0.20.1
Game version: 1,12,2
Server version: 1,12,2
Server type (e.i. PaperSpigot):
Are you using a protocol hack (like ViaVersion)?

**Comment by SkytAsul** [comment]
Can you try again with the 0.21 dev builds please? https://ci.codemc.io/job/SkytAsul/job/BeautyQuests

**Comment by ZeNsN** [comment]
Hello! I installed this version, everything is exactly the same. If I write /guest start (Nick) 1, it will work!

**Comment by ZeNsN** [comment]
I will try to install an older version (to test) If something changes, I will write to you

**Comment by ZeNsN** [comment]
It didn't work out(

**Comment by SkytAsul** [comment]
Alright thanks for testing! Can you send me the yaml file of your quest?

**Comment by SkytAsul** [comment]
Any news about this? Maybe it works with newer dev builds for 1.0?

**Comment by SkytAsul** [comment]
No more information; please reopen if it still happens.
