### ISSUE TITLE
Can't use cat as a quest NPC

### ISSUE THREAD

**Issue by Ajsey** [SkytAsul/BeautyQuests#283]
**Describe the bug**	
So the bug is when i make an NPC that is a cat it just doesnt work. When i click him it just says that this NPC is not starting any mission.

**Reproduction**
----

**Screenshots, error messages**
Nothing is in console, and sending screenshot would be bad idea since i have the plugin in Polish.

**Software**
BeautyQuests version: 0.20.1
Game version: 1.20.1
Server version: 1.20.1
Server type (e.i. PaperSpigot): Paper
Are you using a protocol hack (like ViaVersion)? Nope

**Additional context (optional)**
------

**Comment by SkytAsul** [comment]
Can you shoot a video of you reproducing the bug please?

**Comment by SkytAsul** [comment]
Got no more information; please reopen if the issue still happens.
