### ISSUE TITLE
1.20.2 support

### ISSUE THREAD

**Issue by KeyKatyu** [SkytAsul/BeautyQuests#284]
**Describe the bug**	
The plugin does not support version 1.20.2. Indeed, it disables certain features and the scoreboard does not work.

**Reproduction**
Download the latest version of the plugin and Paper 1.20.2

**Software**
BeautyQuests version: 0.20.1
Game version: 1.20.2
Server version: 234
Server type (e.i. PaperSpigot): Paper
Are you using a protocol hack (like ViaVersion)? No
.

(FR: Si vous êtes plus facilement compréhensible en français, écrivez dans cette langue car il s'agit de ma langue natale)

Je suis français, on peut discuter en français en dessous.

**Comment by KeyKatyu** [comment]
S'il te plaît, accepte le pull request en attente.
Je ne connais pas ce mec, mais il a fait beaucoup de commit et notamment un support de la 1.20.2

**Comment by KeyKatyu** [comment]
Le scoreboard ne fonctionne pas, même dans la dernière version de build dev que je viens de tester (380)

**Comment by KeyKatyu** [comment]
Résolu en partie dans le dernier build dev #381, mais pas de version stable.

**Comment by SkytAsul** [comment]
Au final pas mal de gens ont testé la 1.0 et il ne semble plus y avoir de bugs majeurs donc on peut la considérer comme ~stable.
