### ISSUE TITLE
Enchanting

### ISSUE THREAD

**Issue by ArberCraft** [SkytAsul/BeautyQuests#285]
**Describe the bug**	
A clear and concise description of what the bug is and how it occurs.
Enchanting is not reconized

**Reproduction**
Steps to reproduce the behavior. (If not already explained above.)
Make a Enchanting quest

**Screenshots, error messages**
Are there error messages in the console or in the chat?
Nothing happens and just sits there

**Software**
BeautyQuests version: Latest
Game version: 1.20.2
Server version: 1.20
Server type (e.i. PaperSpigot): paper
Are you using a protocol hack (like ViaVersion)?
Yes

**Additional context (optional)**
Just does not work

(FR: Si vous êtes plus facilement compréhensible en français, écrivez dans cette langue car il s'agit de ma langue natale)

**Comment by SkytAsul** [comment]
Not enough information. Please at least provide the quest file...

**Comment by ArberCraft** [comment]
customItem:
  ==: org.bukkit.inventory.ItemStack
  v: 3465
  type: CARVED_PUMPKIN
startableFromGUI: true
endRewards:
- id: commandReward
  commands:
  - console: true
    label: customcrates give {PLAYER} Fall 1
name: Fall Quests 3
manager:
  branches:
    '0':
      stages:
        '0':
          npcID: 13
          items:
          - ==: org.bukkit.inventory.ItemStack
            v: 3465
            type: PUMPKIN_SEEDS
            amount: 64
          stageType: ITEMS
          text: Started "Seed getter" section of the "Fall Quests 3" Set
        '1':
          objects:
            13309e1f-03cb-49d5-9050-f03e1c57570c:
              amount: 128
              object: OAK_LEAVES
          stageType: PLACE_BLOCKS
          text: Started "Repopulate" section of the "Fall Quests 3" Set
        '2':
          objects:
            ffffffff-aea7-9f17-0000-0000000009ae:
              amount: 1
              object:
                v: 3465
                type: NETHERITE_HOE
                meta:
                  ==: ItemMeta
                  meta-type: UNSPECIFIC
                  ItemFlags:
                  - HIDE_ENCHANTS
                  - HIDE_ATTRIBUTES
                  - HIDE_UNBREAKABLE
                  - HIDE_DESTROYS
                  - HIDE_PLACED_ON
                  - HIDE_POTION_EFFECTS
                  - HIDE_DYE
                  - HIDE_ARMOR_TRIM
          itemComparisons:
            enchants: true
          stageType: ENCHANT
      endingStages: {}
id: 2

**Comment by SkytAsul** [comment]
What are you trying to achieve? You want your players to enchant a netherite hoe, no matter the enchantment they get?

**Comment by AhmadMoney** [comment]
Yes

**Comment by SkytAsul** [comment]
Then change the "item comparisons" to only have "item material" selected.

**Comment by ArberCraft** [comment]
Still Not Fixed

**Comment by SkytAsul** [comment]
Ah, shoot. It still does nothing? Could you send your quest file again?

**Comment by AhmadMoney** [comment]
type: PUMPKIN_SEEDS
            amount: 64
          stageType: ITEMS
          text: Started "Seed getter" section of the "Fall Quests 3" Set
        '1':
          objects:
            13309e1f-03cb-49d5-9050-f03e1c57570c:
              amount: 1
              object: OAK_LEAVES
          stageType: PLACE_BLOCKS
          text: Started "Repopulate" section of the "Fall Quests 3" Set
        '2':
          objects:
            ffffffff-aea7-9f17-0000-0000000009ae:
              amount: 1
              object:
                v: 3465
                type: NETHERITE_HOE
                meta:
                  ==: ItemMeta
                  meta-type: UNSPECIFIC
                  ItemFlags:
                  - HIDE_ENCHANTS
                  - HIDE_ATTRIBUTES
                  - HIDE_UNBREAKABLE
                  - HIDE_DESTROYS
                  - HIDE_PLACED_ON
                  - HIDE_POTION_EFFECTS
                  - HIDE_DYE
                  - HIDE_ARMOR_TRIM
          item material:
            enchants: true
          stageType: ENCHANT
      endingStages: {}
id: 2

**Comment by SkytAsul** [comment]
> Then change the "item comparisons" to only have "item material" selected.
You haven't done this... you must disable the "enchants" comparison and only have the "item material" selected (green).

**Comment by ArberCraft** [comment]
Please explane

**Comment by ArberCraft** [comment]
customItem:
  ==: org.bukkit.inventory.ItemStack
  v: 3465
  type: CARVED_PUMPKIN
name: Fall Quests 3
startableFromGUI: true
endRewards:
- id: commandReward
  commands:
  - console: true
    label: customcrates give {PLAYER} Fall 1
manager:
  branches:
    '0':
      stages:
        '0':
          npcID: 13
          items:
          - ==: org.bukkit.inventory.ItemStack
            v: 3465
            type: PUMPKIN_SEEDS
            amount: 64
          stageType: ITEMS
          text: Started "Seed getter" section of the "Fall Quests 3" Set
        '1':
          objects:
            0ab97d8c-6508-4bc8-ba90-b56479cc3581:
              amount: 1
              object: OAK_LEAVES
          stageType: PLACE_BLOCKS
          text: Started, "Repopulate" section of "Fall Quest 3"
        '2':
          objects:
            00000000-29bf-579c-0000-0000000009ae:
              amount: 1
              object:
                v: 3465
                type: NETHERITE_HOE
          stageType: ENCHANT
          text: ENCHANTIMG@!!
      endingStages: {}
id: 2

**Comment by ArberCraft** [comment]
Remade the quest and this is what happened

**Comment by SkytAsul** [comment]
In the GUI with the list of stages, in the line of your specific enchantment stage, there are multiple buttons, including one to select a list of items and one to toggle "item comparisons". Click on the latter, and then, in the GUI that opens, disable every enabled item and only turn on the "item material" one.

**Comment by ArberCraft** [comment]
No. Server is under soft shutdown and won’t be opened till end of December.

**Comment by SkytAsul** [comment]
Hi, have you got any news?

**Comment by SkytAsul** [comment]
Closed due to inactivity. Please ask to reopen if the issue is still there.
