### ISSUE TITLE
BeautyQuests doesn't support Znpcs

### ISSUE THREAD

**Issue by Nerd10000** [SkytAsul/BeautyQuests#289]
**Software**
BeautyQuests version:
Game version: 1.20.1
Server version: 1.20.1
Server type (e.i. PaperSpigot): Purpur
Are you using a protocol hack (like ViaVersion)?  yes I use Viaversion and Protocollib

**Additional context (optional)**![image](https://github.com/SkytAsul/BeautyQuests/assets/96385928/096635b8-161c-46c1-ab16-aa20436494a3)

**Comment by koegojghiejhgoijh** [comment]
![image](https://github.com/SkytAsul/BeautyQuests/assets/96385928/8a32e83a-6996-409c-b488-9482839a944a)

**Comment by SkytAsul** [comment]
If there is a "BeautyQuests version:" field it's not for letting it blank. I'd also like to know which of znpcs are you using.

**Comment by koegojghiejhgoijh** [comment]
The 4.3

**Comment by SkytAsul** [comment]
And beautyquests version?? I guess it will 0.20, so I propose you to update to beta 1.0, which is available here: https://ci.codemc.io/job/SkytAsul/job/BeautyQuests/
