### ISSUE TITLE
When a player executes a command, bq doesn't detect it!

### ISSUE THREAD

**Issue by Matt3w35** [SkytAsul/BeautyQuests#293]
Hi, I'm using Beauty Quests on a 1.20.1 server and while I was creating a quest I realized that if the quest requires entering the spawn command for example, when the player executes /spawn in chat, the quest does not continue but continues to ask for that command. However, I have seen that this problem does not exist if commands are requested that do not exist on the server. How can I solve it?

**Comment by SkytAsul** [comment]
Can it be because /spawn is handled by your proxy (BungeeCord for example)?

**Comment by Matt3w35** [comment]
No, they are CMI commands, even using /warps gives the same problem

**Comment by SkytAsul** [comment]
And does it do that with non-CMI commands? And what about vanilla commands such as /execute?

**Comment by SkytAsul** [comment]
Ask CMI devs then. I'm using the PlayerCommandPreprocessEvent, which works with everything. I don't know what CMI devs did to break that...
