### ISSUE TITLE
Selecting NPC to Kill Under Mobs Not Working

### ISSUE THREAD

**Issue by CloroxWhitebeard** [SkytAsul/BeautyQuests#294]
**Describe the bug**	
When creating a new quest line I click the objective of killing a mob, which brings me to the option of selecting the mob type through the egg, or the stick icon for selecting an NPC. When selecting the NPC to kill, it will not select it and does nothing. When I do this for other things, such as selecting the NPC to start a quest, it works. My goal is to slay an NPC for the quest..

**Screenshots, error messages**
No error message. I just cannot select the NPC I want killed.

**Software**
BeautyQuests version:  1.0 Snapshot
Game version: 1.20.2
Server version: 
Server type (e.i. PaperSpigot): Spigot
Are you using a protocol hack (like ViaVersion)?

**Comment by SkytAsul** [comment]
Thanks for reporting! This will be fixed in next dev build.

**Comment by SkytAsul** [comment]
This is fixed in [build 386](https://ci.codemc.io/job/SkytAsul/job/BeautyQuests/386/artifact/target/beautyquests-1.0-SNAPSHOT.jar)
