### ISSUE TITLE
Launch and unavailable hologram items glitch

### ISSUE THREAD

**Issue by Daiosity** [SkytAsul/BeautyQuests#295]
**Describe the bug**	
When you set a hologram item and then shift click to remove it , it still persists , the player will still be able to see the old items floating above the NPC , I had to go into the folder and delete the user data for it to fix itself , even though the quest QUI shows that it is on the default value

**Reproduction**
Make a Quest , set the launch and unavailable holograms , quest is repeatable , then after saving it , go back in and remove the hologram items , with shift right click and save , the NPC will still go through the items based on if you can take the quest or not

**Screenshots, error messages**
Are there error messages in the console or in the chat?

**Software**
BeautyQuests version: 1.0 Latest
Game version: 1.20.2
Server version: 1.20.2
Server type (e.i. PaperSpigot): Paper
Are you using a protocol hack (like ViaVersion)? Nope

**Additional context (optional)**
No other context as far as I can tell!

(FR: Si vous êtes plus facilement compréhensible en français, écrivez dans cette langue car il s'agit de ma langue natale)

**Comment by SkytAsul** [comment]
Are the holograms still present after a server restart?

**Comment by SkytAsul** [comment]
Any news?
