### ISSUE TITLE
Chat message formatting

### ISSUE THREAD

**Issue by KeyKatyu** [SkytAsul/BeautyQuests#296]
**Describe the bug**	
Suite aux dernières maj des builds dev, j'ai un problème avec l'affichage des messages du PNJ dans le tchat. Le nom du personnage (en jaune) est maintenant à la fin, et tout est un peu désorganisé. Est-ce un bug ? Je n'avais pas cela avant.

**Screenshots, error messages**
https://i.imgur.com/NZlgpzz.png

**Software**
BeautyQuests version: 386 1.0 Dev build
Game version: 1.20.2
Server version: This server is running Paper version git-Paper-290 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: f186318)
Previous version: git-Paper-280 (MC: 1.20.2)
Server type (e.i. PaperSpigot): Paper
Are you using a protocol hack (like ViaVersion)? No

(FR: Si vous êtes plus facilement compréhensible en français, écrivez dans cette langue car il s'agit de ma langue natale)

**Comment by SkytAsul** [comment]
As-tu supprimé le dossier `/plugins/BeautyQuests/locales` lors de la mise à jour vers la 1.0 ?

**Comment by KeyKatyu** [comment]
J'étais déjà sous 1.0 avant, dois-je quand même le supprimer ?

**Comment by SkytAsul** [comment]
Et tu n'avais pas ce problème avant ? Quelle version de la 1.0 avais-tu auparavant ?

**Comment by KeyKatyu** [comment]
Je n'avais pas ce problème avant en effet.
Je crois que j'avais la version 380 ou 381

**Comment by SkytAsul** [comment]
Peux-tu essayer de supprimer le dossier pour être sûr ?

**Comment by KeyKatyu** [comment]
Je ne risque pas de perdre quoi que ce soit ?
(Quêtes, données de joueurs, etc.)

**Comment by SkytAsul** [comment]
Le dossier `locales` contient uniquement tous les messages avec leurs traductions dans les différentes langues. Tu peux le supprimer sans soucis, et redémarrer le serveur après.

**Comment by KeyKatyu** [comment]
J'ai supprimé le dossier `locales `et fait un `/beautyquests reload` par la suite, ça n'a rien changé.

**Comment by SkytAsul** [comment]
Il ne faut pas utiliser la commande pour reload mais redémarrer le serveur.

**Comment by KeyKatyu** [comment]
C'est bon c'est résolu grâce à ta manip, merci beaucoup ;)
