### ISSUE TITLE
Pls help acap

### ISSUE THREAD

**Issue by Greasyfat** [SkytAsul/BeautyQuests#297]
https://gyazo.com/d38b3014d51204975073fcd9907b22ce

https://gyazo.com/4f3a8e6c9cec7f5256c93ebf1b5d29e9

this error does not allow me to join to server, its so annoying when u dont have discord and cant have help god dammit ... pls someone

**Comment by SkytAsul** [comment]
It is not this error that is preventing the player from joining.

**Comment by SkytAsul** [comment]
No news on this, closing
