### ISSUE TITLE
NOT A BUG(?) - Possible to change items in menus?

### ISSUE THREAD

**Issue by reneg1990** [SkytAsul/BeautyQuests#299]
**Describe the bug**	
This is not a bug! I am trying to customize my UIs as much as possible. Am i able to remove the glass panes + change the icons of books and arrows to the right?

I cant seem to find anything in any of the files, unless i am perhaps blind haha

![image](https://github.com/SkytAsul/BeautyQuests/assets/4029116/077682bd-c4c3-4bcb-b8f5-efd332e8853f)

**Comment by reneg1990** [comment]
Also if it is possible to change the icons with model data that would be nice too, so i can implement custom icons etc.

**Comment by SkytAsul** [comment]
Currently no that's not possible to edit the items, unless you want to edit the plugin by yourself...
Making configurable GUIs from YAML files is really an hassle :/

**Comment by reneg1990** [comment]
I see!

So I dont really understand how to edit a plugin by myself haha. Would it be a quick fix for you to potentially just remove the glass for me? Could just be set to air instead.

If its something i could have u do, i will happily pay you for the trouble.

**Comment by SkytAsul** [comment]
Don't you have a plugin developer for your server?

**Comment by reneg1990** [comment]
Aye he wasnt able to figure out of it - if i could have you remove the glass panes as a minimum id happily pay you for the trouble. Would be a private version of your plugin taht u dont have to maintain of course.

If you are interested feel free to add me on discord. Addy's "renadra"
