### ISSUE TITLE
json language files - backport 1.12.2

### ISSUE THREAD

**Issue by madtomic** [SkytAsul/BeautyQuests#30]
backport support for language file for 1.12.2

https://www.spigotmc.org/resources/1-7-x-1-12-language-utils.8859/

**Comment by SkytAsul** [comment]
I do my best to not make the plugin heavy, so I'll not be able to use something like this.
I have tried to use NMS 1.12-1.11.... integrated name registries, but it causes too many issues to be viable, sorry :/
