### ISSUE TITLE
I have a Server On Aternos which also have GeyserMC which allows bedorck clients to join. Recently i have made a small quest and it works on java and bedrock both but the problem is the Scoreboard is incomplete on bedrock Version which makes it impossible to see  

### ISSUE THREAD

**Issue by Devilkings-shubhamos** [SkytAsul/BeautyQuests#305]
**Describe the bug**	
A clear and concise description of what the bug is and how it occurs.

**Reproduction**
Steps to reproduce the behavior. (If not already explained above.)

**Screenshots, error messages**
Are there error messages in the console or in the chat?

**Software**
BeautyQuests version:
Game version:
Server version:
Server type (e.i. PaperSpigot):
Are you using a protocol hack (like ViaVersion)?

**Additional context (optional)**

(FR: Si vous êtes plus facilement compréhensible en français, écrivez dans cette langue car il s'agit de ma langue natale)

**Comment by SkytAsul** [comment]
There is a form when you create an issue, please fill it instead of putting an extremely long title...
Please fill especially screenshot and software versions.

**Comment by SkytAsul** [comment]
Oh god you created two issues...
