### ISSUE TITLE
[Feature Request] Ajout du support de l'event "Paper's AsyncChat"

### ISSUE THREAD

**Issue by NoltoxGit** [SkytAsul/BeautyQuests#308]
Bonjour,
Pouvez-vous ajouter le support du Paper `AsyncChatEvent` et/ou `AsyncChatDecorateEvent` dans la configuration de votre plugin s'il vous plaît ?
Parce que vous utilisez actuellement un ancien listener : `org.bukkit.event.player.AsyncPlayerChatEvent`. 

Exemple pour la nouvelle configuration :
```yml
# Use Paper's async Chat Event
use-async-chat : true/false
```

Merci beaucoup si vous ajoutez ceci ! :)

**Comment by SkytAsul** [comment]
Je veux conserver la compatibilité avec Spigot. Si je fais ce changement, seuls les utilisateurs Paper pourront utiliser le plugin.

Pourquoi est-ce que vous avez besoin de ça ?

**Comment by NoltoxGit** [comment]
> Je veux conserver la compatibilité avec Spigot. Si je fais ce changement, seuls les utilisateurs Paper pourront utiliser le plugin.
> 
> Pourquoi est-ce que vous avez besoin de ça ?

Hello,
Merci pour la réponse _très_ rapide !

J'ai mal formaté mon message (ce que je viens de corriger) mais ça serait un toggle pour pouvoir l'activer/désactiver selon les utilisateurs.
Et j'en ai besoin car j'utilise un plugin qui recommande fortement l'utilisation de cet Event pour qu'il fonctionne mieux.

**Comment by SkytAsul** [comment]
Peut-être que ce plugin en a besoin, mais je vois pas en quoi BeautyQuests bénéficierait de l'utilisation d'un tel event. In fine ils font la même chose car BQ ne modifie pas le formatage, il lit juste le texte d'origine.

**Comment by SkytAsul** [comment]
À ré-ouvrir si vraiment intéressant.
