### ISSUE TITLE
Backuping up Quest folder

### ISSUE THREAD

**Issue by madtomic** [SkytAsul/BeautyQuests#31]
May I suggest to make a backup of the Quest files in another folder call Backup inside the Quest folder. In the event when the server crashes at least the quest files are safe from being deleted. I just tested this again and it's a known bug and still affects the current build. I think, because all the quest files are loaded in the memory and only stop or the auto save at 15 would save this data.

**Comment by SkytAsul** [comment]
https://github.com/SkytAsul/BeautyQuests/commit/7de5253c1c804667ade42e2d99e9682a6da7f615
