### ISSUE TITLE
Null bug 

### ISSUE THREAD

**Issue by chrisZENGOOD** [SkytAsul/BeautyQuests#312]
**Describe the bug**	
[Server] Server thread/[ERROR] A fatal error occurred while loading plugin.
03.02 19:01:00 [Server] [INFO] java.lang.NullPointerException: null
03.02 19:01:00 [Server] [INFO] at fr.skytasul.quests.QuestsConfiguration$DialogsConfig.update(QuestsConfiguration.java:531) ~[beautyquests-0.21-SNAPSHOT.jar:?]
03.02 19:01:00 [Server] [INFO] at fr.skytasul.quests.QuestsConfiguration$DialogsConfig.access$200(QuestsConfiguration.java:510) ~[beautyquests-0.21-SNAPSHOT.jar:?]
03.02 19:01:00 [Server] [INFO] at fr.skytasul.quests.QuestsConfiguration.update(QuestsConfiguration.java:117) ~[beautyquests-0.21-SNAPSHOT.jar:?]
03.02 19:01:00 [Server] [INFO] at fr.skytasul.quests.BeautyQuests.loadConfigParameters(BeautyQuests.java:355) ~[beautyquests-0.21-SNAPSHOT.jar:?]
03.02 19:01:00 [Server] [INFO] at fr.skytasul.quests.BeautyQuests.onEnable(BeautyQuests.java:137) [beautyquests-0.21-SNAPSHOT.jar:?]
03.02 19:01:00 [Server] [INFO] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:177) [JavaPlugin.class:?]
03.02 19:01:00 [Server] [INFO] at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:318) [JavaPluginLoader.class:?]
03.02 19:01:00 [Server] [INFO] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:399) [SimplePluginManager.class:?]
03.02 19:01:00 [Server] [INFO] at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:477) [CraftServer.class:?]
03.02 19:01:00 [Server] [INFO] at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:418) [CraftServer.class:?]
03.02 19:01:00 [Server] [INFO] at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:383) [MinecraftServer.class:?]
03.02 19:01:00 [Server] [INFO] at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:315) [nz.class:?]
03.02 19:01:00 [Server] [INFO] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:590) [MinecraftServer.class:?]
03.02 19:01:00 [Server] [INFO] at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
03.02 19:01:00 [Server] Server thread/[ERROR] Error while loading configuration and initializing values
03.02 19:01:00 [Server] Server thread/[ERROR] This is a fatal error. Now disabling.
03.02 19:01:00 [Server] StartupDone (7.861s)! For help, type "help" or "?"
**Reproduction**
Steps to reproduce the behavior. (If not already explained above.)

**Screenshots, error messages**
Are there error messages in the console or in the chat?

**Software**
BeautyQuests version: 0.21 snapshot
Game version: 1.12.2
Server version: 1.12.2
Server type (e.i. Mohist):
Are you using a protocol hack (like ViaVersion)?

**Additional context (optional)**
Beautyquests keeps disabling 

(FR: Si vous êtes plus facilement compréhensible en français, écrivez dans cette langue car il s'agit de ma langue natale)

**Comment by SkytAsul** [comment]
Please use latest version.
