### ISSUE TITLE
Compatibilité du scoreboard / Selection de quête "traquée"

### ISSUE THREAD

**Issue by BeerDeus** [SkytAsul/BeautyQuests#315]
Hey ! Je viens proposer des petites idées qui me trottent en tête !

Pourquoi ne pas essayer de rajouter une compatibilité du scoreboard avec des Plugins du style AnimatedScoreboard ou autre ?
On pourrait utiliser les placeholders {quest_name} et autres directement depuis leurs configs (je ne sais pas si c'est possible)
Car le Scoreboard de quête prend le dessus (ce qui est une bonne chose) mais ne remet pas le Scoreboard initial (a moins d'executer une commande en récompense de quête qui est la meilleure solution que j'ai trouvé jusque là)
J'avoue ne pas savoir si ce n'est pas à eux de faire cette compatibilité mais je pose ça là en cas.

Aussi, l'ajout d'une possibilité de changer de quête suivie dans le scoreboard depuis le "QuestBook" (avec un Shift click par exemple) serait vraiment top.

Voilou, en tous cas merci pour le taf c'est vraiment top !

**Comment by EnderGriefeur99** [comment]
utilises les placeholders de quêtes dans ton scoreboard

**Comment by SkytAsul** [comment]
Pour le suivi de quête via le menu, c'est prévu :)
