### ISSUE TITLE
SkillAPI renamed to Fabled

### ISSUE THREAD

**Issue by Travja** [SkytAsul/BeautyQuests#317]
I just want to take the opportunity to inform you that SkillAPI has undergone a rename and is now Fabled. The new resource is located at the Maven coordinates below. This change also renames the main entry point for API operations and the packages associated with the classes. The [studio.magemonkey.fabled.Fabled](https://fabled.magemonkey.studio/javadocs/studio/magemonkey/fabled/Fabled.html) class should be used instead of SkillAPI, though the api should remain backwards compatible. These compatibility classes are likely to be removed at some point in the future, so these should be updated. Supporting older versions of SkillAPI prior to the rename may still be important, so I'd recommend setting up a try-catch where you try the Fabled-based implementation and fall back to the SkillAPI implementation on an exception.

```xml
<repository>
    <id>sonatype</id>
    <url>https://s01.oss.sonatype.org/content/repositories/snapshots</url>
</repository>
...
<dependency>
    <groupId>studio.magemonkey</groupId>
    <artifactId>fabled</artifactId>
    <version>1.0.0-R0.21-SNAPSHOT</version>
</dependency>
```

**Comment by SkytAsul** [comment]
Thanks for the heads-up. It seems like you are talking about ProSkillAPI though, not regular SkillAPI?

**Comment by Travja** [comment]
Yes, that's correct.

**Comment by SkytAsul** [comment]
May you try the [#407 build](https://ci.codemc.io/job/SkytAsul/job/BeautyQuests/407/) and tell me if it works correctly?
