### ISSUE TITLE
Startup console error "failed to register event for ultimate timber"

### ISSUE THREAD

**Issue by S2GN** [SkytAsul/BeautyQuests#318]
**Console Error on startup**
[21:24:27 ERROR]: [BeautyQuests] Failed to register events for class fr.skytasul.quests.integrations.BQUltimateTimber because com/songoda/ultimatetimber/events/TreeFellEvent does not exist.

**Software**
BeautyQuests version: 1.0.3-402
Game version: 1.20.4
Server type: PURPUR (Bukkit/Spigot/Paper)
Server version: 1.20.4-2176
Are you using a protocol hack (like ViaVersion)? Velocity Network
JAVA: OpenJDK 21.0.2 LTS
OS: Ubuntu 22.04.4 LTS

**Comment by SkytAsul** [comment]
Yeah, another weird thing with Songoda plugins. It seems like they changed all their code without a notice. I'll do my best to update.

**Comment by S2GN** [comment]
Thank you, much appreciated.

Songoda offers this plugin for free, otherwise I do use their plugins.  I just use it for the cool tree fell animation.  (If you know of something just as good or better, thats more compatible with BQ I'll happily switch.)

**Comment by SkytAsul** [comment]
Try with BeautyQuests 1.0.3, I updated yesterday :)

**Comment by S2GN** [comment]
Thank you!

I've been busy with work, but should have time to update tonight.

Tom V.
(Owner/Operator)
a.k.a. ChromaKatS2GN Design LLC™

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by SkytAsul** [comment]
Please tell me if it fixed your problem so I can close this issue :)

**Comment by SkytAsul** [comment]
I guess it is now fixed. Feel free to reopen.
