### ISSUE TITLE
Bug quest with LeveledMobs

### ISSUE THREAD

**Issue by yannje** [SkytAsul/BeautyQuests#329]
**Describe the bug**	
Les quêtes avec le plugin LeveledMobs ne fonctionne pas et renvoie une erreur

**Reproduction**
Faire une quête avec le plugin puis tester, rien ne fonctionnera et renvoie une erreur

**Screenshots, error messages**
Console : "Could not pass event BQMobDeathEvent to BeautyQuests v1.0.4_BUILD411
java.lang.NoClassDefFoundError: me/lokka30/levelledmobs/LevelledMobs"

**Software**
BeautyQuests version: v1.0.4_BUILD411
Game version: Java
Server version: 1.20.4
Server type (e.i. PaperSpigot): PurpurMC
Are you using a protocol hack (like ViaVersion)? : oui

**Additional context (optional)**
Version LeveledMobs : LevelledMobs-4.0.6.b35

(FR: Si vous êtes plus facilement compréhensible en français, écrivez dans cette langue car il s'agit de ma langue natale)

**Comment by SkytAsul** [comment]
Quelle version de LevelledMobs ?

**Comment by yannje** [comment]
LevelledMobs-4.0.6.b35

**Comment by SkytAsul** [comment]
Ah nickel ils ont pété toute l'API depuis la version 4. J'essaye de fix ça dès que possible.

**Comment by SkytAsul** [comment]
Peux-tu essayer la dev build 412 s'il te plaît ? https://ci.codemc.io/job/SkytAsul/job/BeautyQuests/412/

**Comment by yannje** [comment]
tout fonctionne merci :)
