### ISSUE TITLE
Upgrade 1.21

### ISSUE THREAD

**Issue by centerworld2023** [SkytAsul/BeautyQuests#332]
Bonjour, 

Je viens de déployer (accidentellement) BeautyQuest sur l'un de nos serveur qui est en 1.21 (qui est dans un contexte de migration). 

J'ai remarqué (trop tard) que le plugin n'était pas compatible avec la 1.21. Ainsi, je viens aux nouvelles, qu'en est-il du développement ? Une v1.21 de BeautyQuest est bien prévue ? 

Si oui pouvez vous nous (me) prévenir si la v1.21 venait à sortir prochainement ? 

PS: je n'ai pas trouvé de catégorie pour poser une question. 

Merci

EnyroxFire - Co-Fondateur de CenterWorld

**Comment by EnderGriefeur99** [comment]
version 1.21 dispo sur le discord

**Comment by centerworld2023** [comment]
Pouvez vous nous faire parvenir l'invit' ? Merci.

________________________________________
