### ISSUE TITLE
Issue with commands from CMI

### ISSUE THREAD

**Issue by BobbyZe1606** [SkytAsul/BeautyQuests#337]
**Describe the bug**	
For any CMI commands, if I were to add in the chat quest to type a cmi command, it does not progress with the quest. But other non CMI commands such as /summon it works and the quest progresses. 

**Reproduction**
Create a quest that needs a cmi command to be typed in the chat

**Screenshots, error messages**
No error messages in console.
![image](https://github.com/user-attachments/assets/22d19749-775e-4edc-85b0-cde65cf272ad)

**Software**
BeautyQuests version: 1.0.3
Game version: 1.20.1
Server version: 1.20.1
Server type (e.i. PaperSpigot): Bukkit, Spigot
Are you using a protocol hack (like ViaVersion): No

**Additional context (optional)**

(FR: Si vous êtes plus facilement compréhensible en français, écrivez dans cette langue car il s'agit de ma langue natale)

**Comment by SkytAsul** [comment]
CMI are probably doing some weird shit with their commands and not
registering them properly like literally all the other plugins. You can ask
them why isn't the PlayerCommandPreProcessEvent called for their commands,
if they give me some information I might fix this.

**Comment by BobbyZe1606** [comment]
So CMI replied, and mentioned in order for BQ to work, need to make players type /cmi rankup and similar for other cmi commands. And this resolved the issue.
