### ISSUE TITLE
Could not pass event PlayerAccountJoinEvent to BeautyQuests v1.0.4

### ISSUE THREAD

**Issue by fr3d3lin** [SkytAsul/BeautyQuests#342]
Jai une erreur qui flood la console

BeautyQuests version: 1.0.4
Game version: paper 1.17.1
Are you using a protocol hack (like ViaVersion)? no

 Avoir paper 1.17.1-411, BeautyQuest 1.0.4, MythicMob 5.0.2, Worldedit 7.2.20, Worldguard 7.0.7 et WorldGuardEvents-1.18.1

1# bug, quand un joueur se connect au serveur.

Entre en conflit avec :  MythicMobs-5.0.2
PlayerAccountJoinEvent

2# Bug, Quand le joueur se déplace.

Entre en conflit avec:   WorldGuardEvents-1.18.1
PlayerMoveEvent
 

Erreur dans la Console : https://pastebin.com/fCmHhM1M

la version 1.0.3 ne fessait pas se bug

(FR: Si vous êtes plus facilement compréhensible en français, écrivez dans cette langue car il s'agit de ma langue natale)

**Comment by SkytAsul** [comment]
Met à jour ta version de MythicMobs, ça règlera le problème

**Comment by fr3d3lin** [comment]
la derniere version de MythicMob prise en charge pour paper 1.17.1 est la 5.0.2. 

j'ai esseyer la derniere version de MyhticMob v5.7.2 mais la console se rempli d'erreur et desactive mythicmob

sinon je vais rester avec la version 1.0.3, merci pour votre aide :)
