### ISSUE TITLE
Spigot - 1.17.1

### ISSUE THREAD

**Issue by fr3d3lin** [SkytAsul/BeautyQuests#344]
Salut, j'ai deja envoyé un message car BeautyQuests 1.0.4 ne passe pas l'event PlayerAccountJoinEvent (spigot 1.17.1)

donc je reste avec BeautyQuests 1.0.3 J'ai pas de souci avec ca XD

maintenent, quand je veux selectioner un mob Mythicmob ca ne passe pas 
- Could not pass event PlayerAccountJoinEvent to BeautyQuests v1.0.4
- Could not pass event InventoryClickEvent to BeautyQuests v1.0.3

paper 1.17.1
mythicmob 5.0.2 (derniere officiellement suporter pour ma ver de paper)

sinon, avez vous une exemple de Quest avec un mythicmob.. je pourrais cree une quete manuellement.

**Comment by EnderGriefeur99** [comment]
ta version de MM est dépassé

**Comment by SkytAsul** [comment]
Oui c'est le soucis, MM est trop vieux. Désolé mais il n'y a pas vraiment de correction, si je veux supporter cette version de MM alors les nouvelles versions ne marcheront plus : il fallait faire un choix.

**Comment by fr3d3lin** [comment]
c'est ce que je me disait, merci quand même, je vais esseyer de cree la quete manuellement. car j'ai l’impression que cest juste le gui qui bug

**Comment by fr3d3lin** [comment]
Merci quand meme, joyeux noel :D

**Comment by SkytAsul** [comment]
C'est bon à savoir ! Joyeux Noël à toi :)
