### ISSUE TITLE
Bug: holoTalkItemName

### ISSUE THREAD

**Issue by madtomic** [SkytAsul/BeautyQuests#35]
If you use command to force start a quest for a player.

Repeat the same command and it will bug out holoTalkItemName if you have a find a npc quest.

This does not proper reset when player completes the quest.

**Comment by madtomic** [comment]
Add a better check, if a quest is already started. Player should not start the same quest again. 
>This should taken care of this issue.

**Comment by SkytAsul** [comment]
https://github.com/SkytAsul/BeautyQuests/commit/dce4034137126aa806b7d005d53e6aea7a91d276
