### ISSUE TITLE
Improve resetPlayer and resetPlayerQuest permissions

### ISSUE THREAD

**Issue by madtomic** [SkytAsul/BeautyQuests#37]
I had tried beautyquests.command.resetPlayerQuest and it didn't work as expected

There should be two separate permissions for this.

resetPlayer - default to OP
resetPlayerQuest - Player only

**Add permission - beautyquests.command.resetPlayerQuest
Add command  - quest resetPlayerQuest playername 1
Also add support for Console**

I want the player to able to use this to reset their own quest but I don't want them to reset other player quest.

If they run this command. quest resetPlayerQuest playername 1

**I am aware of allowPlayerCancelQuest but I needed a command for player/console to use similar to
/quest resetPlayerQuest playername 1**

**Comment by SkytAsul** [comment]
In fact, you want players to be able to cancel their own quests ?

**Comment by madtomic** [comment]
This is a console command that I need separately than the current one as it give anyone the ability to reset other players if they have the resetPlayer perm. I need a reset perm that is strictly for their own quests and they can use to cancel their own quests

**Comment by madtomic** [comment]
Commit by SkytZAsul https://github.com/SkytAsul/BeautyQuests/commit/949fc06bed52cfa2f34cc837499c988f06d9342b
