### ISSUE TITLE
command noPermission message SPAMS

### ISSUE THREAD

**Issue by madtomic** [SkytAsul/BeautyQuests#38]
![image](https://user-images.githubusercontent.com/6004542/50552962-fc926f80-0c6b-11e9-871d-ed42c04cd8c9.png)

![image](https://user-images.githubusercontent.com/6004542/50552886-df10d600-0c6a-11e9-925b-2d70602ebe29.png)

When set noPermission to NOTHING. This spams in chat when they use the command.
/quest resetPlayerQuest playername 1

**Comment by SkytAsul** [comment]
Fixed
