### ISSUE TITLE
End Rewards

### ISSUE THREAD

**Issue by GGEasyMan** [SkytAsul/BeautyQuests#4]
**Describe the bug**
When i save the End Rewards and close the editor, works perfectly. The problem is that when i open the editor again, all End Rewards losts the save and i have to set all End Rewards again.

BeautyQuests version: 0.8.1
Server version: 1.12.2

**Comment by SkytAsul** [comment]
End rewards of each stage ?

**Comment by GGEasyMan** [comment]
Yeah, End Rewards of each stage!

**Comment by SkytAsul** [comment]
Okay I'll see that

**Comment by SkytAsul** [comment]
Fixed ! Thanks for reporting :+1:
