### ISSUE TITLE
Bug: 0.14 Preview 6 - requirement permission is not working

### ISSUE THREAD

**Issue by madtomic** [SkytAsul/BeautyQuests#44]
It spits out this error when trying to type a permission for the quest.

![image](https://user-images.githubusercontent.com/6004542/50862879-d0ad7300-136a-11e9-88cc-44aa07221e42.png)

**Comment by SkytAsul** [comment]
You have to type "add _permissionxxx_"
(it's a permission list, so you can add multiple permissions and then "close"
