### ISSUE TITLE
reduce spams

### ISSUE THREAD

**Issue by madtomic** [SkytAsul/BeautyQuests#46]
Should try to reduce the spams. maybe check if message was already sent and cancel the next one.

![image](https://user-images.githubusercontent.com/6004542/51035731-eee8be00-1578-11e9-834f-9951c5c0ad59.png)

**Comment by SkytAsul** [comment]
When is it sent ?

**Comment by madtomic** [comment]
When player right click on the quest giver npc or quest turn in npc
