### ISSUE TITLE
<bug> Obtain message, fix?

### ISSUE THREAD

**Issue by madtomic** [SkytAsul/BeautyQuests#49]
As you can see here. 10 money and 10 experience points but money is missing.

![image](https://user-images.githubusercontent.com/6004542/51928248-792b8180-23c3-11e9-9f00-fd8b3988b931.png)

**Comment by SkytAsul** [comment]
What economy plugin are you using ?

**Comment by madtomic** [comment]
Essentials

**Comment by SkytAsul** [comment]
It is a problem with the Essentials economy system, so you can ask them to change it, but I think you'd better do to switch to another economy plugin.
