### ISSUE TITLE
TODO for setting up the Crowdin integration

### ISSUE THREAD

**Issue by Vainock** [SkytAsul/BeautyQuests#57]
This is not only for setting up the integration. It's also good for keeping "not code things" out of the code.

- [x] 1. Extract the source texts from the code and put them in the locales folder as en_US.yml.
- [x] 2. Stop defining the default english texts in the code and read now the texts from the files in the locales folder.

**Comment by SkytAsul** [comment]
Finished! https://crowdin.com/project/beautyquests
