### ISSUE TITLE
more holoitems

### ISSUE THREAD

**Issue by madtomic** [SkytAsul/BeautyQuests#58]
- [x]  quest holoitem for quest not available for player or met requisite 

- [ ] talk to holoitem for Bring Back Items stage when the player doesn't have the needed item (loud CPU usage, so maybe a slow task)

>Rename holoLaunchItemName to something more understandable.
holoNewQuest: # new quests available
holoNewQuestNot: # quest prerequisite not yet met

>Rename holoTalkItemName to something more understandable.
holoTalkTo: # met quest conditions
holoTalkToNot: # don't met quest conditions

ench: 'DAMAGE_ALL:1' # Make the holo item glow
You can try something more understandable - glow: true

```java
holoNewQuest:
    holo-item:
      type: ELYTRA
      data: 1
      ench: 'DAMAGE_ALL:1' # Make the holo item glow
holoNewQuestNot:
    holo-item:
      type: ELYTRA
      data: 2
holoTalkTo:
    holo-item:
      type: ELYTRA
      data: 3
      ench: 'DAMAGE_ALL:1' # Make the holo item glow
holoTalkToNot:
    holo-item:
      type: ELYTRA
      data: 4
```

- [x] hologram configurable for each quest

**Comment by EnderGriefeur99** [comment]
and use the name of the item
holoTalkTo:
    holo-item:
      type: STICK
      data: 3
      displayname: "BIG_POINT"

**Comment by SkytAsul** [comment]
Addition:
- [ ] hologram configurable for each quest

**Comment by SkytAsul** [comment]
"holoTalkToNot" doesn't make sense to me, there is no reason to show an hologram to a player if there is no stage on a NPC...
Reopen the issue if you think I have not understood well.
