### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by ThunderBuddy34** [SkytAsul/BeautyQuests#6]
So is the gui broken because I tried to open the menu which it did but for some reason when i try to click on the next arrow or create a new quest and click the slimeball it just picks up the item and i can move it into my inv and nothing happens any fixes?

**Comment by SkytAsul** [comment]
Do you have any console error ? And what version of Spigot are you using ?

**Comment by ThunderBuddy34** [comment]
1.12.2

**Comment by SkytAsul** [comment]
Is this fixed ?

**Comment by ThunderBuddy34** [comment]
No

**Comment by EnderGriefeur99** [comment]
@ThunderBuddy34 you use spigot or craftbukkit or paperspigot or glowstone ?

**Comment by SkytAsul** [comment]
No answer
