### ISSUE TITLE
<bug> Plugin doesn't save that you gave items to NPC instantly

### ISSUE THREAD

**Issue by Vainock** [SkytAsul/BeautyQuests#61]
**Describe the bug**	
When you give the needed items to the NPC and start talking to him and then rejoin the server, you have to give the items again.

**Reproduction**
(Already told)

**Expected behavior**
That it saves the given items...

**Screenshots, error messages**
/

**Softwares**
BeautyQuests version: newest
Game version: /
Server version: /
Server type (e.g. PaperSpigot): /
Are you using a protocol hack (like ViaVersion)?
/

**Additional context (optional)**
/

**Comment by SkytAsul** [comment]
Fixed on 0.15
