### ISSUE TITLE
<feature> MythicMob name

### ISSUE THREAD

**Issue by Byxis** [SkytAsul/BeautyQuests#63]
Bonjour !
J'aime beaucoup votre plugin, mais lors de la création d'une quête où nous devons tuer un Mob, il est impossible de sélectionner un mob grâce a son nom, et donc je ne peux pas faire de différence entre par exemple un zombie de la mine, et un zombie de ville.

Comme solution, je propose tout simplement de rajouter un onglet dans le GUI qui propose de préciser le nom du mob tué. Si cela est fait, la mission n'affiche donc pas par exemple "zombie x50" mais "NomCustom x50"
Voilà c'est tout,
Je ne pense pas que ce soit trop difficile à faire,

Merci beaucoup d'avoir lu cette recommandation,
Bonne chance et merci !

**Comment by SkytAsul** [comment]
Donc afficher un nom différent de l'identifiant du mob en quelque sorte ? Je ne sais pas si MythicMob dispose de deux paramètres différents.

**Comment by Byxis** [comment]
Oui, mais aussi de pouvoir préciser le nom nécessaire pour faire avancer la quête :
Si je tue 20 Zombie, ça n'affecte pas ma mission qui consiste a tué 20 Zombie s’appelant CustomName 

(Je suis vraiment désolé pour le retard je n'avais pas vu votre réponse ! ;( )

**Comment by SkytAsul** [comment]
Donc je résume :
Tu as un mob MythicMob dont le nom _interne_ est genre zombie1.
Dans la quête tu veux afficher _NomCustom_.
C'est ça ?

**Comment by Byxis** [comment]
Hmmm...
je vais résumé exactement ce que j'aimerai : 
Quand je créé ma quête, je choisis le type de mob donc Zombie et je choisis qu'il doit avoir le nom Zombie1 pour faire avancer la quête.
Donc si je tue un Zombie normal, la mission n'avance pas. Mais si je tue un Zombie nommé Zombie1 sa avance.

Et sur la mission, il y ai écris uniquement : Vous devez tuer Zombie1 x50  (donc le nom custom directement)

**Comment by SkytAsul** [comment]
Ah mais tu n'utilises pas du tout MythicMob en fait ?

**Comment by Byxis** [comment]
Non ! On peut le faire avec ?

**Comment by SkytAsul** [comment]
Ah ben oui, tu peux faire plein de trucs géniaux avec MM 😂

**Comment by Byxis** [comment]
Okay merci beaucoup, je vais l'installer ! Et désolé de t'avoir fais perdre ton temps 😓😓
