### ISSUE TITLE
<bug> maven project setup

### ISSUE THREAD

**Issue by madtomic** [SkytAsul/BeautyQuests#66]
version: BeautyQuests v0.15_PRE1

https://github.com/SkytAsul/BeautyQuests/tree/master/src/main/ressources

I think you meant to use "resources"
https://github.com/SkytAsul/BeautyQuests/tree/master/src/main/resources

**Comment by SkytAsul** [comment]
Maven automatically created "ressources" 🤔

**Comment by SkytAsul** [comment]
Fixed, thanks ^^
