### ISSUE TITLE
<feature> Change the output style of the "/bq help" command

### ISSUE THREAD

**Issue by Vainock** [SkytAsul/BeautyQuests#70]
**Is your feature request related to a problem?**
Currently when writting "/bq help" [I get boomed with tons of help commands](https://i.ibb.co/0nnPGBt/BQ.png) and line breaks. It is the aim of such a help command, the problem here is that every entry starts with a prefix, that makes everything much longer than needed, a possible solution would be:

**Describe a possible solution**
I would completely remove the prefix thing:
[prefix] BeautyQuests - help
/bq create: Create a quest
/bq edit: Edit a quest
...

**Comment by SkytAsul** [comment]
You're right. Fixed.
