### ISSUE TITLE
<bug> "Last gain: null" message when editing amount of XP points

### ISSUE THREAD

**Issue by Vainock** [SkytAsul/BeautyQuests#73]
**Describe the bug**	
When I edit the XP points of a quest and I have not setted a value before, there is written "Last gain: null"

**Screenshots, error messages**
https://i.ibb.co/0CRtBjY/BQ.png
Are there error messages in the console? No

**Softwares**
BeautyQuests version: 0.15.1_PRE1
Game version: 1.14
Server version: 1,14
Server type (e.g. PaperSpigot): Spigot
Are you using a protocol hack (like ViaVersion)? No

**Comment by SkytAsul** [comment]
I will change _null_ to _0_.
