### ISSUE TITLE
Switch quest tracker to current active quest

### ISSUE THREAD

**Issue by madtomic** [SkytAsul/BeautyQuests#75]
When a player does an action related to an active quest. It will update the quest tracker so it will show the current active quest that is in progress.

**Comment by SkytAsul** [comment]
You mean, it will display the quest state in chat when updated?

**Comment by madtomic** [comment]
No, the quest cycles in quest tracker. It should show whatever is active.

**Comment by SkytAsul** [comment]
But what do you mean by quest tracker? Scoreboard?

**Comment by madtomic** [comment]
Scoreboard, yes

**Comment by SkytAsul** [comment]
Published in pre-released!
