### ISSUE TITLE
Multiple choice stages - quest branches system

### ISSUE THREAD

**Issue by djnico46** [SkytAsul/BeautyQuests#76]
Bonsoir , 
2 petites demandes de modification de ton super plugin 👍  : 

- Stop quête ,  pouvoir stopper une quête en cours de route  et quelle soit automatiquement reset pour le joueur  ;  ex  /quests stop   ou directement clickable dans le GUI

- Pouvoir créer des quêtes a multiple choix :  ex  "aller voir un npc "  si le joueur choisi   1 ou l'autre npc  , le déroulement de la quête diffère 

- et un dernier pour la route :  pouvoir modifier  l'item en Hologram ou ( les particules  je sait pas si faisable par le gui )    par quêtes ( uniquement au départ ) 

Voila , Merci d'avance  et encore une fois super boulot !

Quêtes à multiple choix :

- [x] Structure générale

- [x] Interface utilisateur (textes de description, commandes)

- [x] GUIs pour créer les branches

**Comment by SkytAsul** [comment]
Salut !

- Pour ça tu peux utiliser `/quests cancel <idDeLaQuête>` en donnant la permission `beautyquests.command.cancel` aux joueurs, ou alors, plus simple, active l'option `allowPlayerCancelQuest` du fichier config.yml. Avec ça, les joueurs auront juste à cliquer sur l'items dans le GUI /quests.

- Beaucoup de joueurs me demandent ça ! C'est donc prévu, j'espère pouvoir le faire dans la prochaine grosse MAJ.

- Heu j'ai pas tout compris, mais je compte faire en sorte de pouvoir modifier les items hologrammes pour chaque quête si c'est ça que tu demandais.

Merci à toi ^^

**Comment by djnico46** [comment]
pour le point 3 , oui c'est tout a fait ca ! 
ok pour le 1 j’avais zappé la fonction :/ 

ce serait top pour le 2 :) 

Merci encore

**Comment by SkytAsul** [comment]
Terminé depuis longtemps, inclus dans la version 0.16.
