### ISSUE TITLE
Objectif de quête aléatoire

### ISSUE THREAD

**Issue by Spakye** [SkytAsul/BeautyQuests#79]
Salut!
Je vous félicite et remercie pour ce plugin, il est top !

J'ai une petite question, j’espère qu'elle n'a pas déjà était posé ( j'ai cherché pas trouvé ).
C'est possible de rendre un objectif de quête aléatoire ? 
J'ai par exemple une quête toute simple répétable toutes les 6h qui envoi les joueurs pécher un saumon puis le ramener au npc contre un peu d'xp.
Du coup j'aimerai que ça ne soit pas tous le temps un saumon mais un poisson choisit aléatoirement.
J'ai un autre quête qui envoi les joueurs tuer des zombies, pareil j'aimerai que ce soit un mob choisit aléatoirement.

J'imagine bien que rajouter ça au client ça doit être compliqué mais au niveau du fichier YML de l a quête je peux peu être bricoler un truc non ?
Merci :)

**Comment by SkytAsul** [comment]
Ca devrait être possible, par contre ce ne sera pas pour tout de suite !

**Comment by SkytAsul** [comment]
J'ai rajouté ça avec le système de quest pools du coup, dans les dev build de la 0.19 ^^
