### ISSUE TITLE
Start quests with a simple command

### ISSUE THREAD

**Issue by AbelMG** [SkytAsul/BeautyQuests#8]
**Is your feature request related to a problem? Please describe.**
Allow the players start quests to X players with a simple command like for example:
/beautyquests start (player) (quest)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

(FR: Si vous êtes plus facilement compréhensible en français, écrivez dans cette langue car il s'agit de ma langue natale)

**Comment by SkytAsul** [comment]
Added in the preview number 7 - on my Discord server

**Comment by SkytAsul** [comment]
Added in 0.12
