### ISSUE TITLE
Tasks, mine X blocks of X type

### ISSUE THREAD

**Issue by AbelMG** [SkytAsul/BeautyQuests#9]
**Is your feature request related to a problem? Please describe.**
Simple task where you have to mine x amount of blocks writing the type

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

(FR: Si vous êtes plus facilement compréhensible en français, écrivez dans cette langue car il s'agit de ma langue natale)

**Comment by SkytAsul** [comment]
Preview version with this stage type available on my Discord server : https://discord.gg/H8fXrkD

**Comment by SkytAsul** [comment]
Added in 0.12
