### ISSUE TITLE
Sub-commands "editor" and "inventory" are no longer useable

### ISSUE THREAD

**Issue by Vainock** [SkytAsul/BeautyQuests#92]
I already know that the sub-command "inventory" does no longer exist, but I can still tab through it.
The command "editor" also no longer works, but I can also tab complete it.

Please remove them from the tab completion list.

**Comment by SkytAsul** [comment]
Those commands still exist and are still functionnal:

- _/bq inventory_ serves to reopen the GUI system when it has closed due to a problem
-  _/bq editor_ serves to force exit the editor
