### ISSUE TITLE
[BUG] Restart time not showing

### ISSUE THREAD

**Issue by LoneDev6** [SkytAsul/BeautyQuests#98]
**Describe the bug**	
 click to talk with NPC you won't get message "you need to wait 100 minutes", no message is sent, so players are confused

**Reproduction**
- Create 2 quests
- set the same citizens NPC as quests starter 
- set "several-use" to false in the first quest settings
- set "several-use" to true in the first quest settings and set for example 100 minutes as delay
- complete the first quest and the second quest
- then click again to talk with NPC you won't get message "you need to wait 100 minutes", no message is sent, so players are confused

**Software**
BeautyQuests version: 0.16_BUILD26
Game version: 1.14.4
Server version: 1.14.4
Server type (e.i. PaperSpigot): Paper
Are you using a protocol hack (like ViaVersion)? No

**Comment by SkytAsul** [comment]
Fixed in https://github.com/SkytAsul/BeautyQuests/commit/8d6a0d929bbc8403789afe3dacc8fe4405976eb7

**Comment by LoneDev6** [comment]
Omg thanks a lot, can you also check why this happens?
![image](https://user-images.githubusercontent.com/27242001/66864414-667acc00-ef95-11e9-9943-b7bdf3f86d78.png)


also happens setting exp level
